// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Quick Start',
      link: {
        type: 'generated-index'
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'quick-start' }]
    },
    {
      type: 'category',
      label: 'Deploy',
      link: {
        type: 'generated-index'
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'deploy' }]
    },
    {
      type: 'category',
      label: 'Datasets',
      link: {
        type: 'generated-index'
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'datasets' }]
    },
    {
      type: 'category',
      label: 'Flow Settings',
      link: {
        type: 'generated-index'
      },
      items: [{ type: 'autogenerated', dirName: 'flow-settings' }]
    },
    {
      type: 'category',
      label: 'Other',
      link: {
        type: 'generated-index'
      },
      items: [{ type: 'autogenerated', dirName: 'other' }]
    }
  ]
};

module.exports = sidebars;
