// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Develop',
      link: {
        type: 'generated-index'
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Proxy',
          link: {
            type: 'generated-index'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'develop/proxy'
            }
          ]
        },
        'develop/dev',
        {
          type: 'category',
          label: 'Deploy',
          collapsed: false,
          link: {
            type: 'generated-index'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'develop/deploy'
            }
          ]
        },
        'develop/oneapi'
      ]
    },
    {
      type: 'category',
      label: 'Deploy',
      link: {
        type: 'generated-index'
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'deploy' }]
    },
    {
      type: 'category',
      label: 'Datasets',
      link: {
        type: 'generated-index'
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'datasets' }]
    },
    {
      type: 'category',
      label: 'Flow Modules',
      link: {
        type: 'generated-index'
      },
      items: [{ type: 'autogenerated', dirName: 'flow-modules' }]
    },
    {
      type: 'category',
      label: 'Other',
      link: {
        type: 'generated-index'
      },
      items: [{ type: 'autogenerated', dirName: 'other' }]
    }
  ]
};

module.exports = sidebars;
