import { describe, expect, it } from 'vitest';
import { normalizeToolCardTags } from '@fastgpt/web/components/core/plugin/tool/utils';

describe('normalizeToolCardTags', () => {
  it('filters empty tag labels generated by missing marketplace tag mappings', () => {
    expect(normalizeToolCardTags(['', '工具', '  ', '生产力'])).toEqual(['工具', '生产力']);
  });

  it('returns an empty list for nullish tags', () => {
    expect(normalizeToolCardTags(null)).toEqual([]);
    expect(normalizeToolCardTags(undefined)).toEqual([]);
  });
});
