// CAMB AI language codes - auto-generated from /source-languages endpoint

export const CambLanguageCodes = {
  en_us: 1, // english (united states)
  af_za: 2, // afrikaans (south africa)
  am_et: 3, // amharic (ethiopia)
  ar_ae: 4, // arabic (united arab emirates)
  ar_bh: 5, // arabic (bahrain)
  ar_dz: 6, // arabic (algeria)
  ar_eg: 7, // arabic (egypt)
  ar_iq: 8, // arabic (iraq)
  ar_jo: 9, // arabic (jordan)
  ar_kw: 10, // arabic (kuwait)
  ar_lb: 11, // arabic (lebanon)
  ar_ly: 12, // arabic (libya)
  ar_ma: 13, // arabic (morocco)
  ar_om: 14, // arabic (oman)
  ar_qa: 15, // arabic (qatar)
  ar_sa: 16, // arabic (saudi arabia)
  ar_sy: 17, // arabic (syria)
  ar_tn: 18, // arabic (tunisia)
  ar_ye: 19, // arabic (yemen)
  az_az: 20, // azerbaijani (latin, azerbaijan)
  bg_bg: 21, // bulgarian (bulgaria)
  bn_bd: 22, // bangla (bangladesh)
  bn_in: 23, // bengali (india)
  bs_ba: 24, // bosnian (bosnia and herzegovina)
  ca_es: 25, // catalan
  cs_cz: 26, // czech (czechia)
  cy_gb: 27, // welsh (united kingdom)
  da_dk: 28, // danish (denmark)
  de_at: 29, // german (austria)
  de_ch: 30, // german (switzerland)
  de_de: 31, // german (germany)
  el_gr: 32, // greek (greece)
  en_au: 33, // english (australia)
  en_ca: 34, // english (canada)
  en_gb: 35, // english (united kingdom)
  en_hk: 36, // english (hong kong sar)
  en_ie: 37, // english (ireland)
  en_in: 38, // english (india)
  en_ke: 39, // english (kenya)
  en_ng: 40, // english (nigeria)
  en_nz: 41, // english (new zealand)
  en_ph: 42, // english (philippines)
  en_sg: 43, // english (singapore)
  en_tz: 44, // english (tanzania)
  en_za: 45, // english (south africa)
  es_ar: 46, // spanish (argentina)
  es_bo: 47, // spanish (bolivia)
  es_cl: 48, // spanish (chile)
  es_co: 49, // spanish (colombia)
  es_cr: 50, // spanish (costa rica)
  es_cu: 51, // spanish (cuba)
  es_do: 52, // spanish (dominican republic)
  es_ec: 53, // spanish (ecuador)
  es_es: 54, // spanish (spain)
  es_gq: 55, // spanish (equatorial guinea)
  es_gt: 56, // spanish (guatemala)
  es_hn: 57, // spanish (honduras)
  es_mx: 58, // spanish (mexico)
  es_ni: 59, // spanish (nicaragua)
  es_pa: 60, // spanish (panama)
  es_pe: 61, // spanish (peru)
  es_pr: 62, // spanish (puerto rico)
  es_py: 63, // spanish (paraguay)
  es_sv: 64, // spanish (el salvador)
  es_us: 65, // spanish (united states)
  es_uy: 66, // spanish (uruguay)
  es_ve: 67, // spanish (venezuela)
  et_ee: 68, // estonian (estonia)
  eu_es: 69, // basque
  fa_ir: 70, // persian (iran)
  fi_fi: 71, // finnish (finland)
  fr_be: 73, // french (belgium)
  fr_ca: 74, // french (canada)
  fr_ch: 75, // french (switzerland)
  fr_fr: 76, // french (france)
  gl_es: 78, // galician
  gu_in: 79, // gujarati (india)
  he_il: 80, // hebrew (israel)
  hi_in: 81, // hindi (india)
  hr_hr: 82, // croatian (croatia)
  hu_hu: 83, // hungarian (hungary)
  hy_am: 84, // armenian (armenia)
  id_id: 85, // indonesian (indonesia)
  is_is: 86, // icelandic (iceland)
  it_it: 87, // italian (italy)
  ja_jp: 88, // japanese (japan)
  ka_ge: 90, // georgian (georgia)
  kk_kz: 91, // kazakh (kazakhstan)
  km_kh: 92, // khmer (cambodia)
  kn_in: 93, // kannada (india)
  ko_kr: 94, // korean (korea)
  lo_la: 95, // lao (laos)
  lt_lt: 96, // lithuanian (lithuania)
  lv_lv: 97, // latvian (latvia)
  mk_mk: 98, // macedonian (north macedonia)
  ml_in: 99, // malayalam (india)
  mn_mn: 100, // mongolian (mongolia)
  mr_in: 101, // marathi (india)
  ms_my: 102, // malay (malaysia)
  mt_mt: 103, // maltese (malta)
  my_mm: 104, // burmese (myanmar)
  nb_no: 105, // norwegian (bokmål, norway)
  ne_np: 106, // nepali (nepal)
  nl_be: 107, // dutch (belgium)
  nl_nl: 108, // dutch (netherlands)
  pl_pl: 109, // polish (poland)
  ps_af: 110, // pashto (afghanistan)
  pt_br: 111, // portuguese (brazil)
  pt_pt: 112, // portuguese (portugal)
  ro_ro: 113, // romanian (romania)
  ru_ru: 114, // russian (russia)
  si_lk: 115, // sinhala (sri lanka)
  sk_sk: 116, // slovak (slovakia)
  sl_si: 117, // slovenian (slovenia)
  so_so: 118, // somali (somalia)
  sq_al: 119, // albanian (albania)
  sr_rs: 120, // serbian (cyrillic, serbia)
  su_id: 121, // sundanese (indonesia)
  sv_se: 122, // swedish (sweden)
  sw_ke: 123, // swahili (kenya)
  sw_tz: 124, // swahili (tanzania)
  ta_in: 125, // tamil (india)
  ta_lk: 126, // tamil (sri lanka)
  ta_my: 127, // tamil (malaysia)
  ta_sg: 128, // tamil (singapore)
  te_in: 129, // telugu (india)
  th_th: 130, // thai (thailand)
  tr_tr: 131, // turkish (turkey)
  uk_ua: 132, // ukrainian (ukraine)
  ur_in: 133, // urdu (india)
  ur_pk: 134, // urdu (pakistan)
  uz_uz: 135, // uzbek (latin, uzbekistan)
  vi_vn: 136, // vietnamese (vietnam)
  zh_cn: 139, // chinese (mandarin, simplified)
  zh_cn_henan: 140, // chinese (zhongyuan mandarin henan, simplified)
  zh_cn_liaoning: 141, // chinese (northeastern mandarin, simplified)
  zh_cn_shaanxi: 142, // chinese (zhongyuan mandarin shaanxi, simplified)
  zh_cn_shandong: 143, // chinese (jilu mandarin, simplified)
  zh_cn_sichuan: 144, // chinese (southwestern mandarin, simplified)
  zh_hk: 145, // chinese (cantonese, traditional)
  zh_tw: 146, // chinese (taiwanese mandarin, traditional)
  pa_in: 148, // punjabi (india)
  tl_ph: 151 // tagalog (philippines)
} as const;

export type CambLanguageCode = (typeof CambLanguageCodes)[keyof typeof CambLanguageCodes];

// Language label map for UI display
export const CambLanguageLabels: Record<number, string> = Object.fromEntries(
  Object.entries(CambLanguageCodes).map(([key, value]) => [value, key.replace(/_/g, '-')])
);

// Select options for workflow node UI
export const cambLanguageSelectOptions = Object.entries(CambLanguageCodes).map(([key, value]) => ({
  label: key.replace(/_/g, '-'),
  value: String(value)
}));
