packages:
  - packages/*
  - projects/*
  - pro/admin
  - pro/sso
  - scripts/icon
  - sdk/*

catalog:
  "@fastgpt-sdk/logger": 0.1.2
  "@fastgpt-sdk/otel": 0.1.2
  "@fastgpt-sdk/storage": 0.6.15
  "@modelcontextprotocol/sdk": ^1
  "@node-rs/jieba": 2.0.1
  "@svgr/webpack": ^6.5.1
  "@tanstack/react-query": ^4.24.10
  "@types/js-yaml": ^4.0.9
  "@types/jsonwebtoken": ^9.0.3
  "@types/lodash": ^4
  "@types/mime-types": ^3.0.1
  "@types/node": ^20
  "@types/react": ^18
  "@types/react-dom": ^18
  "@types/request-ip": ^0.0.38
  "@typescript-eslint/eslint-plugin": ^6.21.0
  "@typescript-eslint/parser": ^6.21.0
  "@vitest/coverage-v8": ^4.1.5
  ahooks: ^3.9.5
  "@chakra-ui/anatomy": ^2
  "@chakra-ui/icons": ^2
  "@chakra-ui/next-js": ^2
  "@chakra-ui/react": ^2
  "@chakra-ui/styled-system": ^2
  "@chakra-ui/system": ^2
  "@emotion/react": ^11
  "@emotion/styled": ^11
  axios: 1.13.6
  chalk: ^5.6.2
  date-fns: ^3.6.0
  dayjs: 1.11.19
  eslint: ^8.57.0
  eslint-config-next: 15.5.12
  express: ^4
  file-type: 21.3.0
  i18next: 23.16.8
  js-yaml: ^4.1.1
  jsonwebtoken: ^9.0.3
  json5: ^2.2.3
  lodash: 4.17.23
  mime: ^4.1.0
  mime-types: 3.0.2
  minio: 8.0.7
  mongodb-memory-server: ^10.1.4
  mongoose: ^8.10.1
  nanoid: ^5.1.3
  next: 16.2.4
  next-i18next: 15.4.2
  proxy-agent: ^6
  react: ^18
  react-dom: ^18
  react-hook-form: 7.43.1
  react-i18next: 14.1.2
  react-markdown: ^9.0.1
  recharts: ^2.15.0
  remark-gfm: ^4.0.1
  request-ip: ^3.3.0
  tsdown: 0.21.4
  tsx: ^4.20.6
  typescript: ^5.9.3
  vitest: ^4.1.5
  zod: ^4

onlyBuiltDependencies:
  - "@parcel/watcher"
  - bufferutil
  - canvas
  - core-js
  - esbuild
  - mongodb-memory-server
  - msgpackr-extract
  - protobufjs
  - puppeteer
  - sharp
  - utf-8-validate
  - vue-demi

overrides:
  "@types/react": ^18
  "@types/react-dom": ^18
  react: ^18
  react-dom: ^18
