name: 'Sandbox-Test'
on:
  pull_request:
    paths:
      - 'projects/code-sandbox/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pnpm install

      - name: Install Python Dependencies
        run: pip install -r projects/code-sandbox/requirements.txt

      - name: Build native Python sandbox library
        run: |
          export HTTP_PROXY="${{ vars.AB_HTTP_PROXY }}"
          export HTTPS_PROXY="${{ vars.AB_HTTPS_PROXY }}"
          export NO_PROXY="${{ vars.AB_NO_PROXY }}"
          if ! which go; then
            echo "Acquire::http::Proxy \"${{ vars.AB_HTTP_PROXY }}\";" | tee /etc/apt/apt.conf.d/99proxy
            echo "Acquire::https::Proxy \"${{ vars.AB_HTTP_PROXY }}\";" | tee -a /etc/apt/apt.conf.d/99proxy
            apt-get update -qq && apt-get install -y -qq golang-go libseccomp-dev
          fi
          cd projects/code-sandbox && pnpm run build:native:python

      - name: Run Unit Tests
        run: pnpm --filter=code-sandbox test
