import type { Processor } from 'bullmq';
import type { EmbeddingTrainTaskJobData } from './mq';
import { MongoEmbeddingTrainTask } from './schema';
import {
  getEmbeddingTrainTask,
  updateEmbeddingTaskStatus,
  updateEmbeddingCheckpointStage,
  updateEmbeddingCheckpointData
} from './controller';
import {
  EmbeddingTrainTaskStatusEnum,
  EmbeddingTaskCheckpointStageEnum
} from '@fastgpt/global/core/train/embedding/constants';
import { addLog } from '../../../../common/system/log';

import { runGenerateTrainsetStage } from './stages/generate-trainset';
import { runGenerateEvalDatasetStage } from './stages/generate-evaldataset';
import { runEvalBaseModelStage } from './stages/eval-basemodel';
import { runFinetuneStage } from './stages/finetune';
import { runRegisterStage } from './stages/register';
import { runEvalTunedModelStage } from './stages/eval-tunedmodel';
import { runLLMJudgeStage } from './stages/llm-judge';
import {
  EmbeddingTrainErrEnum,
  EmbeddingTrainSuggestionEnum
} from '@fastgpt/global/common/error/code/train';
import { createEmbeddingEnhancedError } from '../utils';
import { TrainTaskUnrecoverableError } from '../../common/errors';

/**
 * Embedding training task processor
 *
 * Executes complete embedding model training pipeline:
 * 1. generate_trainset  - Generate / wait for training set (includes JSONL export)
 * 2. generate_evaldataset - Generate evaluation dataset (auto: DiTing; exact: skip)
 * 3. eval_basemodel    - Evaluate base model to establish baseline
 * 4. finetuning        - Model fine-tuning via SFT Bridge (taskType='embedding')
 * 5. registering       - Model registration in FastGPT
 * 6. eval_tunedmodel   - Evaluate fine-tuned model
 */
export const embeddingTrainTaskProcessor: Processor<EmbeddingTrainTaskJobData> = async (job) => {
  const { taskId } = job.data;

  const task = await getEmbeddingTrainTask(taskId);
  if (!task) {
    const enhancedError = createEmbeddingEnhancedError(
      null,
      EmbeddingTrainErrEnum.embeddingProcessorTaskNotFound,
      EmbeddingTrainSuggestionEnum.embeddingProcessorTaskNotFound
    );
    throw new TrainTaskUnrecoverableError(enhancedError);
  }

  const currentStage = task.checkpoint.stage;

  addLog.info('Embedding task execution started', {
    taskId,
    attemptsMade: job.attemptsMade,
    checkpointStage: task.checkpoint.stage,
    currentStage,
    totalAttempts: job.opts.attempts
  });

  try {
    if (task.status === EmbeddingTrainTaskStatusEnum.pending) {
      await updateEmbeddingTaskStatus(taskId, EmbeddingTrainTaskStatusEnum.running);
    }

    // Stage 1: generate_trainset
    if (shouldRunStage(currentStage, EmbeddingTaskCheckpointStageEnum.generate_trainset)) {
      const result = await runGenerateTrainsetStage(task);
      await updateEmbeddingCheckpointData(taskId, 'generate_trainset', {
        trainDatasetId: result.trainDatasetId,
        trainDatasetFilePath: result.trainDatasetFilePath,
        autoGenerated: result.autoGenerated
      });
      await updateEmbeddingCheckpointStage(
        taskId,
        EmbeddingTaskCheckpointStageEnum.generate_trainset
      );
    }

    // Stage 2: generate_evaldataset
    if (shouldRunStage(currentStage, EmbeddingTaskCheckpointStageEnum.generate_evaldataset)) {
      const taskAfterStage1 = await getEmbeddingTrainTask(taskId);
      if (!taskAfterStage1) {
        const enhancedError = createEmbeddingEnhancedError(
          EmbeddingTaskCheckpointStageEnum.generate_evaldataset,
          EmbeddingTrainErrEnum.embeddingProcessorTaskLostAfterPrepare,
          EmbeddingTrainSuggestionEnum.embeddingProcessorTaskLostAfterPrepare
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const result = await runGenerateEvalDatasetStage(taskAfterStage1);
      await updateEmbeddingCheckpointData(taskId, 'generate_evaldataset', {
        evalDatasetId: result.evalDatasetId,
        autoGenerated: result.autoGenerated
      });
      await updateEmbeddingCheckpointStage(
        taskId,
        EmbeddingTaskCheckpointStageEnum.generate_evaldataset
      );
    }

    // Stage 3: eval_basemodel
    if (shouldRunStage(currentStage, EmbeddingTaskCheckpointStageEnum.eval_basemodel)) {
      const taskAfterStage2 = await getEmbeddingTrainTask(taskId);
      if (!taskAfterStage2) {
        const enhancedError = createEmbeddingEnhancedError(
          EmbeddingTaskCheckpointStageEnum.eval_basemodel,
          EmbeddingTrainErrEnum.embeddingProcessorTaskLostAfterEvalGen,
          EmbeddingTrainSuggestionEnum.embeddingProcessorTaskLostAfterEvalGen
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const result = await runEvalBaseModelStage(taskAfterStage2);
      await updateEmbeddingCheckpointData(taskId, 'eval_basemodel', {
        baseModelEvalResult: result.baseModelEvalResult,
        rankingResults: result.rankingResults
      });
      await updateEmbeddingCheckpointStage(taskId, EmbeddingTaskCheckpointStageEnum.eval_basemodel);
    }

    // Stage 4: finetuning
    if (shouldRunStage(currentStage, EmbeddingTaskCheckpointStageEnum.finetuning)) {
      const taskAfterStage3 = await getEmbeddingTrainTask(taskId);
      if (!taskAfterStage3) {
        const enhancedError = createEmbeddingEnhancedError(
          EmbeddingTaskCheckpointStageEnum.finetuning,
          EmbeddingTrainErrEnum.embeddingProcessorTaskLostAfterEval,
          EmbeddingTrainSuggestionEnum.embeddingProcessorTaskLostAfterEval
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const finetuneResult = await runFinetuneStage(taskAfterStage3);
      await updateEmbeddingCheckpointData(taskId, 'finetuning', {
        sftTaskId: finetuneResult.sftTaskId,
        tunedModelEndpoint: finetuneResult.tunedModelEndpoint
      });
      await updateEmbeddingCheckpointStage(taskId, EmbeddingTaskCheckpointStageEnum.finetuning);
    }

    // Stage 5: registering
    if (shouldRunStage(currentStage, EmbeddingTaskCheckpointStageEnum.registering)) {
      const taskAfterFinetune = await getEmbeddingTrainTask(taskId);
      if (!taskAfterFinetune) {
        const enhancedError = createEmbeddingEnhancedError(
          EmbeddingTaskCheckpointStageEnum.registering,
          EmbeddingTrainErrEnum.embeddingProcessorTaskLostAfterFinetune,
          EmbeddingTrainSuggestionEnum.embeddingProcessorTaskLostAfterFinetune
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const registerResult = await runRegisterStage(taskAfterFinetune);
      await updateEmbeddingCheckpointData(taskId, 'registering', {
        tunedModelId: registerResult.tunedModelId
      });
      await updateEmbeddingCheckpointStage(taskId, EmbeddingTaskCheckpointStageEnum.registering);
    }

    // Stage 6: eval_tunedmodel
    if (shouldRunStage(currentStage, EmbeddingTaskCheckpointStageEnum.eval_tunedmodel)) {
      const taskAfterRegister = await getEmbeddingTrainTask(taskId);
      if (!taskAfterRegister) {
        const enhancedError = createEmbeddingEnhancedError(
          EmbeddingTaskCheckpointStageEnum.eval_tunedmodel,
          EmbeddingTrainErrEnum.embeddingProcessorTaskLostAfterRegister,
          EmbeddingTrainSuggestionEnum.embeddingProcessorTaskLostAfterRegister
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const result = await runEvalTunedModelStage(taskAfterRegister);
      await updateEmbeddingCheckpointData(taskId, 'eval_tunedmodel', {
        tunedModelEvalResult: result.tunedModelEvalResult,
        rankingResults: result.rankingResults
      });
      await updateEmbeddingCheckpointStage(
        taskId,
        EmbeddingTaskCheckpointStageEnum.eval_tunedmodel
      );
    }

    // Stage 7: llm_judge
    if (shouldRunStage(currentStage, EmbeddingTaskCheckpointStageEnum.llm_judge)) {
      const taskAfterStage6 = await getEmbeddingTrainTask(taskId);
      if (!taskAfterStage6) {
        const enhancedError = createEmbeddingEnhancedError(
          EmbeddingTaskCheckpointStageEnum.llm_judge,
          EmbeddingTrainErrEnum.embeddingProcessorTaskLostAfterEval,
          EmbeddingTrainSuggestionEnum.embeddingProcessorTaskLostAfterEval
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const judgeResult = await runLLMJudgeStage(taskAfterStage6);
      await updateEmbeddingCheckpointData(taskId, 'llm_judge', {
        judgedExpectedIds: judgeResult.judgedExpectedIds,
        baseModelRejudgedResult: judgeResult.baseModelRejudgedResult,
        tunedModelRejudgedResult: judgeResult.tunedModelRejudgedResult
      });
      await updateEmbeddingCheckpointStage(taskId, EmbeddingTaskCheckpointStageEnum.llm_judge);
    }

    // Write final result
    const finalTask = await getEmbeddingTrainTask(taskId);
    if (!finalTask) {
      const enhancedError = createEmbeddingEnhancedError(
        null,
        EmbeddingTrainErrEnum.embeddingProcessorTaskLostAfterEval,
        EmbeddingTrainSuggestionEnum.embeddingProcessorTaskLostAfterEval
      );
      throw new TrainTaskUnrecoverableError(enhancedError);
    }
    const finalCheckpoint = finalTask.checkpoint.data || {};
    await MongoEmbeddingTrainTask.updateOne(
      { _id: taskId },
      {
        status: EmbeddingTrainTaskStatusEnum.completed,
        updateTime: new Date(),
        finishTime: new Date(),
        result: {
          trainDatasetId: finalCheckpoint.generate_trainset?.trainDatasetId ?? undefined,
          trainDatasetFilePath:
            finalCheckpoint.generate_trainset?.trainDatasetFilePath ?? undefined,
          tunedModelId: finalCheckpoint.registering?.tunedModelId ?? undefined,
          evalDatasetId: finalCheckpoint.generate_evaldataset?.evalDatasetId ?? undefined,
          baseModelEvalResult: finalCheckpoint.eval_basemodel?.baseModelEvalResult,
          tunedModelEvalResult: finalCheckpoint.eval_tunedmodel?.tunedModelEvalResult,
          baseModelRejudgedResult: finalCheckpoint.llm_judge?.baseModelRejudgedResult,
          tunedModelRejudgedResult: finalCheckpoint.llm_judge?.tunedModelRejudgedResult
        }
      }
    );

    addLog.info('Embedding train task completed', { taskId });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    const isUnrecoverable = error instanceof TrainTaskUnrecoverableError;

    addLog.error('Embedding train task failed', {
      taskId,
      error: errorMessage,
      isUnrecoverable,
      errorType: error instanceof Error ? error.constructor.name : 'Unknown'
    });

    throw error;
  }
};

/**
 * Determine whether to run a stage (skip completed stages, run remaining stages)
 */
function shouldRunStage(
  currentStage: `${EmbeddingTaskCheckpointStageEnum}` | null,
  targetStage: `${EmbeddingTaskCheckpointStageEnum}`
): boolean {
  if (currentStage === null) return true;

  const stageOrder: EmbeddingTaskCheckpointStageEnum[] = [
    EmbeddingTaskCheckpointStageEnum.generate_trainset,
    EmbeddingTaskCheckpointStageEnum.generate_evaldataset,
    EmbeddingTaskCheckpointStageEnum.eval_basemodel,
    EmbeddingTaskCheckpointStageEnum.finetuning,
    EmbeddingTaskCheckpointStageEnum.registering,
    EmbeddingTaskCheckpointStageEnum.eval_tunedmodel,
    EmbeddingTaskCheckpointStageEnum.llm_judge
  ];

  const currentStageEnum = currentStage as EmbeddingTaskCheckpointStageEnum;
  const targetStageEnum = targetStage as EmbeddingTaskCheckpointStageEnum;

  return stageOrder.indexOf(targetStageEnum) > stageOrder.indexOf(currentStageEnum);
}
