import { connectionMongo, getMongoModel } from '../../../../common/mongo';
import type { EmbeddingTrainTaskSchemaType } from '@fastgpt/global/core/train/embedding/type';
import {
  EmbeddingTrainTaskStatusEnum,
  EmbeddingTaskCheckpointStageEnum,
  EmbeddingTrainMethodEnum
} from '@fastgpt/global/core/train/embedding/constants';

/** Embedding training task schema */
const EmbeddingTrainTaskSchema = new connectionMongo.Schema({
  trainsetId: {
    type: connectionMongo.Schema.Types.ObjectId,
    ref: 'embedding_trainset',
    required: false // optional: exact mode passes at create; auto mode written by generate_trainset stage
  },
  teamId: {
    type: connectionMongo.Schema.Types.ObjectId,
    ref: 'team',
    required: true
  },
  tmbId: {
    type: connectionMongo.Schema.Types.ObjectId,
    ref: 'team_member',
    required: true
  },
  name: {
    type: String,
    required: true
  },
  baseModelId: {
    type: String,
    required: true
  },
  baseModelEndpoint: {
    type: {
      base_url: {
        type: String,
        required: false
      },
      model: {
        type: String,
        required: true
      },
      api_key: {
        type: String,
        required: false
      }
    },
    required: true
  },
  evalDatasetId: {
    type: String,
    required: false // exact mode: passed at create; auto mode: written by generate_evaldataset stage
  },
  datasetIds: {
    type: [String],
    required: false // auto mode only: source for generate_trainset/generate_evaldataset
  },
  newModelName: {
    type: String,
    required: false // optional name for the trained model
  },
  generateConfig: {
    type: connectionMongo.Schema.Types.Mixed,
    required: false // trainset synthesis config: indexType, negativeStrategy, sampleSize, etc.
  },
  trainMethod: {
    type: String,
    enum: Object.values(EmbeddingTrainMethodEnum),
    default: EmbeddingTrainMethodEnum.lora,
    required: false // defaults to lora for backward compatibility
  },
  status: {
    type: String,
    enum: Object.values(EmbeddingTrainTaskStatusEnum),
    default: EmbeddingTrainTaskStatusEnum.pending
  },
  checkpoint: {
    type: {
      stage: {
        type: String,
        enum: [...Object.values(EmbeddingTaskCheckpointStageEnum), null],
        default: null
      },
      data: {
        generate_trainset: {
          trainDatasetId: String,
          trainDatasetFilePath: String,
          autoGenerated: Boolean
        },
        generate_evaldataset: {
          evalDatasetId: String,
          autoGenerated: Boolean
        },
        eval_basemodel: {
          baseModelEvalResult: connectionMongo.Schema.Types.Mixed,
          rankingResults: [
            {
              itemId: String,
              rankedIds: [String],
              chunks: [{ id: String, q: String, a: String }]
            }
          ]
        },
        finetuning: {
          sftTaskId: String,
          tunedModelEndpoint: {
            base_url: String,
            model: String,
            api_key: String
          }
        },
        registering: {
          tunedModelId: String
        },
        eval_tunedmodel: {
          tunedModelEvalResult: connectionMongo.Schema.Types.Mixed,
          rankingResults: [
            {
              itemId: String,
              rankedIds: [String],
              chunks: [{ id: String, q: String, a: String }]
            }
          ]
        },
        llm_judge: {
          judgedExpectedIds: [
            {
              itemId: String,
              expectedIds: [String]
            }
          ],
          baseModelRejudgedResult: connectionMongo.Schema.Types.Mixed,
          tunedModelRejudgedResult: connectionMongo.Schema.Types.Mixed
        }
      },
      stageEndTime: {
        generate_trainset: Date,
        generate_evaldataset: Date,
        eval_basemodel: Date,
        finetuning: Date,
        registering: Date,
        eval_tunedmodel: Date,
        llm_judge: Date
      }
    },
    default: {
      stage: null,
      data: {},
      stageEndTime: {}
    }
  },
  result: {
    type: {
      trainDatasetId: String,
      trainDatasetFilePath: String,
      tunedModelId: String,
      evalDatasetId: String,
      baseModelEvalResult: connectionMongo.Schema.Types.Mixed,
      tunedModelEvalResult: connectionMongo.Schema.Types.Mixed,
      baseModelRejudgedResult: connectionMongo.Schema.Types.Mixed,
      tunedModelRejudgedResult: connectionMongo.Schema.Types.Mixed
    }
  },
  errorMsg: {
    type: connectionMongo.Schema.Types.Mixed
  },
  jobId: {
    type: String
  },
  createTime: {
    type: Date,
    default: () => new Date()
  },
  updateTime: {
    type: Date,
    default: () => new Date()
  },
  finishTime: {
    type: Date
  }
});

// Indexes
EmbeddingTrainTaskSchema.index({ baseModelId: 1, status: 1, createTime: -1 });
EmbeddingTrainTaskSchema.index({ trainsetId: 1, createTime: -1 });
EmbeddingTrainTaskSchema.index({ teamId: 1, status: 1 });
EmbeddingTrainTaskSchema.index({ status: 1, updateTime: 1 });
EmbeddingTrainTaskSchema.index({ jobId: 1 });
EmbeddingTrainTaskSchema.index({ 'checkpoint.stage': 1, status: 1 });
EmbeddingTrainTaskSchema.index({ teamId: 1, status: 1, createTime: -1 });
EmbeddingTrainTaskSchema.index({ 'checkpoint.data.registering.tunedModelId': 1 });
EmbeddingTrainTaskSchema.index({ teamId: 1, 'checkpoint.data.registering.tunedModelId': 1 });
EmbeddingTrainTaskSchema.index({ teamId: 1, baseModelId: 1 });

export const MongoEmbeddingTrainTask = getMongoModel<EmbeddingTrainTaskSchemaType>(
  'embedding_train_task',
  EmbeddingTrainTaskSchema
);
