export enum OperationLogEventEnum {
  LOGIN = 'LOGIN',
  CREATE_INVITATION_LINK = 'CREATE_INVITATION_LINK',
  JOIN_TEAM = 'JOIN_TEAM',
  CHANGE_MEMBER_NAME = 'CHANGE_MEMBER_NAME',
  KICK_OUT_TEAM = 'KICK_OUT_TEAM',
  CREATE_DEPARTMENT = 'CREATE_DEPARTMENT',
  CHANGE_DEPARTMENT = 'CHANGE_DEPARTMENT',
  DELETE_DEPARTMENT = 'DELETE_DEPARTMENT',
  RELOCATE_DEPARTMENT = 'RELOCATE_DEPARTMENT',
  CREATE_GROUP = 'CREATE_GROUP',
  DELETE_GROUP = 'DELETE_GROUP',
  ASSIGN_PERMISSION = 'ASSIGN_PERMISSION'
}
