import timezones from 'timezones-list';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc.js';
import timezone from 'dayjs/plugin/timezone.js';

// timezones-list is CJS; under ESM interop the default import may receive
// {default: [...]} instead of the array. Normalize at import time.
const tz = (timezones as any)?.default ?? timezones;
if (!Array.isArray(tz)) {
  throw new Error('timezones-list default import failed: expected array');
}

dayjs.extend(utc);
dayjs.extend(timezone);

/**
 * Returns the offset from UTC in hours for the current locale.
 * @param {string} timeZone Timezone to get offset for
 * @returns {number} The offset from UTC in hours.
 *
 * Generated by Trelent
 */
export const getTimezoneOffset = (timeZone: string): number => {
  const now = new Date();
  const tzString = now.toLocaleString('en-US', {
    timeZone
  });
  const localString = now.toLocaleString('en-US');
  const diff = (Date.parse(localString) - Date.parse(tzString)) / 3600000;
  const offset = diff + now.getTimezoneOffset() / 60;
  // Ensure we return +0 instead of -0 for UTC
  return offset === 0 ? 0 : -offset;
};

/**
 * Returns a list of timezones sorted by their offset from UTC.
 * @returns {object[]} A list of the given timezones sorted by their offset from UTC.
 *
 * Generated by Trelent
 */
export const getTimeZoneList = () => {
  const result = tz
    .map((timezone) => {
      try {
        const display = dayjs().tz(timezone.tzCode).format('Z');

        return {
          name: `(UTC${display}) ${timezone.tzCode}`,
          value: timezone.tzCode,
          time: getTimezoneOffset(timezone.tzCode)
        };
      } catch (e) {}
    })
    .filter((item) => item);

  result.sort((a, b) => {
    if (!a || !b) return 0;
    if (a.time > b.time) {
      return 1;
    }

    if (b.time > a.time) {
      return -1;
    }

    return 0;
  });

  return [
    {
      name: 'UTC',
      time: 0,
      value: 'UTC'
    },
    ...result
  ] as {
    name: string;
    value: string;
    time: number;
  }[];
};
export const timeZoneList = getTimeZoneList();

export const getTimezoneCodeFromStr = (timeString: string | Date) => {
  if (typeof timeString !== 'string' || !timeString.includes(':')) {
    return '+00:00';
  }

  // Match timezone offset pattern at the end of string: +HH:MM or -HH:MM
  const timezoneMatch = timeString.match(/([+-]\d{2}:\d{2})$/);

  if (timezoneMatch) {
    return timezoneMatch[1];
  }

  return '+00:00';
};

/**
 * 返回指定时区的当前时间文本。
 * 直接按目标时区格式化，不依赖进程本地时区：给本地时间再叠加时区偏移，会在非 UTC 进程里多算一次偏移。
 */
export const getSystemTime = (timeZone: string) => {
  return dayjs().tz(timeZone).format('YYYY-MM-DD HH:mm:ss dddd');
};
