import type { Processor } from 'bullmq';
import type { RerankTrainTaskJobData } from './mq';
import { MongoRerankTrainTask } from './schema';
import {
  getRerankTrainTask,
  updateRerankTaskStatus,
  updateRerankCheckpointStage,
  updateRerankCheckpointData
} from './controller';
import {
  RerankTrainTaskStatusEnum,
  RerankTaskCheckpointStageEnum
} from '@fastgpt/global/core/train/rerank/constants';
import { addLog } from '../../../../common/system/log';

import { runGenerateTrainsetStage } from './stages/generate-trainset';
import { runGenerateEvalDatasetStage } from './stages/generate-evaldataset';
import { runEvalBaseModelStage } from './stages/eval-basemodel';
import { runFinetuneStage } from './stages/finetune';
import { runRegisterStage } from './stages/register';
import { runEvalTunedModelStage } from './stages/eval-tunedmodel';
import {
  RerankTrainErrEnum,
  RerankTrainSuggestionEnum
} from '@fastgpt/global/common/error/code/train';
import { createRerankEnhancedError } from '../utils';
import { TrainTaskUnrecoverableError } from '../../common/errors';

/**
 * Rerank training task processor
 *
 * Executes complete rerank model training pipeline:
 * 1. generate_trainset  - Generate / wait for training set (includes JSONL export)
 * 2. generate_evaldataset - Generate evaluation dataset (auto: DiTing; exact: skip)
 * 3. eval_basemodel    - Evaluate base model to establish baseline
 * 4. finetuning        - Model fine-tuning via SFT Bridge
 * 5. registering       - Model registration in FastGPT
 * 6. eval_tunedmodel   - Evaluate fine-tuned model
 */
export const rerankTrainTaskProcessor: Processor<RerankTrainTaskJobData> = async (job) => {
  const { taskId } = job.data;

  const task = await getRerankTrainTask(taskId);
  if (!task) {
    const enhancedError = createRerankEnhancedError(
      null,
      RerankTrainErrEnum.rerankProcessorTaskNotFound,
      RerankTrainSuggestionEnum.rerankProcessorTaskNotFound
    );
    throw new TrainTaskUnrecoverableError(enhancedError);
  }

  const currentStage = task.checkpoint.stage;

  addLog.info('Rerank task execution started', {
    taskId,
    attemptsMade: job.attemptsMade,
    checkpointStage: task.checkpoint.stage,
    currentStage,
    totalAttempts: job.opts.attempts
  });

  try {
    if (task.status === RerankTrainTaskStatusEnum.pending) {
      await updateRerankTaskStatus(taskId, RerankTrainTaskStatusEnum.running);
    }

    // Stage 1: generate_trainset
    if (shouldRunStage(currentStage, RerankTaskCheckpointStageEnum.generate_trainset)) {
      const result = await runGenerateTrainsetStage(task);
      await updateRerankCheckpointData(taskId, 'generate_trainset', {
        trainDatasetId: result.trainDatasetId,
        trainDatasetFilePath: result.trainDatasetFilePath,
        autoGenerated: result.autoGenerated
      });
      await updateRerankCheckpointStage(taskId, RerankTaskCheckpointStageEnum.generate_trainset);
    }

    // Stage 2: generate_evaldataset
    if (shouldRunStage(currentStage, RerankTaskCheckpointStageEnum.generate_evaldataset)) {
      const taskAfterStage1 = await getRerankTrainTask(taskId);
      if (!taskAfterStage1) {
        const enhancedError = createRerankEnhancedError(
          RerankTaskCheckpointStageEnum.generate_evaldataset,
          RerankTrainErrEnum.rerankProcessorTaskLostAfterPrepare,
          RerankTrainSuggestionEnum.rerankProcessorTaskLostAfterPrepare
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const result = await runGenerateEvalDatasetStage(taskAfterStage1);
      await updateRerankCheckpointData(taskId, 'generate_evaldataset', {
        evalDatasetId: result.evalDatasetId,
        autoGenerated: result.autoGenerated
      });
      await updateRerankCheckpointStage(taskId, RerankTaskCheckpointStageEnum.generate_evaldataset);
    }

    // Stage 3: eval_basemodel
    if (shouldRunStage(currentStage, RerankTaskCheckpointStageEnum.eval_basemodel)) {
      const taskAfterStage2 = await getRerankTrainTask(taskId);
      if (!taskAfterStage2) {
        const enhancedError = createRerankEnhancedError(
          RerankTaskCheckpointStageEnum.eval_basemodel,
          RerankTrainErrEnum.rerankProcessorTaskLostAfterEvalGen,
          RerankTrainSuggestionEnum.rerankProcessorTaskLostAfterEvalGen
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const result = await runEvalBaseModelStage(taskAfterStage2);
      await updateRerankCheckpointData(taskId, 'eval_basemodel', {
        baseModelEvalResult: result.baseModelEvalResult
      });
      await updateRerankCheckpointStage(taskId, RerankTaskCheckpointStageEnum.eval_basemodel);
    }

    // Stage 4: finetuning
    if (shouldRunStage(currentStage, RerankTaskCheckpointStageEnum.finetuning)) {
      const taskAfterStage3 = await getRerankTrainTask(taskId);
      if (!taskAfterStage3) {
        const enhancedError = createRerankEnhancedError(
          RerankTaskCheckpointStageEnum.finetuning,
          RerankTrainErrEnum.rerankProcessorTaskLostAfterEval,
          RerankTrainSuggestionEnum.rerankProcessorTaskLostAfterEval
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const finetuneResult = await runFinetuneStage(taskAfterStage3);
      await updateRerankCheckpointData(taskId, 'finetuning', {
        sftTaskId: finetuneResult.sftTaskId,
        tunedModelEndpoint: finetuneResult.tunedModelEndpoint
      });
      await updateRerankCheckpointStage(taskId, RerankTaskCheckpointStageEnum.finetuning);
    }

    // Stage 5: registering
    if (shouldRunStage(currentStage, RerankTaskCheckpointStageEnum.registering)) {
      const taskAfterFinetune = await getRerankTrainTask(taskId);
      if (!taskAfterFinetune) {
        const enhancedError = createRerankEnhancedError(
          RerankTaskCheckpointStageEnum.registering,
          RerankTrainErrEnum.rerankProcessorTaskLostAfterFinetune,
          RerankTrainSuggestionEnum.rerankProcessorTaskLostAfterFinetune
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const registerResult = await runRegisterStage(taskAfterFinetune);
      await updateRerankCheckpointData(taskId, 'registering', {
        tunedModelId: registerResult.tunedModelId
      });
      await updateRerankCheckpointStage(taskId, RerankTaskCheckpointStageEnum.registering);
    }

    // Stage 6: eval_tunedmodel
    if (shouldRunStage(currentStage, RerankTaskCheckpointStageEnum.eval_tunedmodel)) {
      const taskAfterRegister = await getRerankTrainTask(taskId);
      if (!taskAfterRegister) {
        const enhancedError = createRerankEnhancedError(
          RerankTaskCheckpointStageEnum.eval_tunedmodel,
          RerankTrainErrEnum.rerankProcessorTaskLostAfterRegister,
          RerankTrainSuggestionEnum.rerankProcessorTaskLostAfterRegister
        );
        throw new TrainTaskUnrecoverableError(enhancedError);
      }

      const result = await runEvalTunedModelStage(taskAfterRegister);
      await updateRerankCheckpointData(taskId, 'eval_tunedmodel', {
        tunedModelEvalResult: result.tunedModelEvalResult
      });
      await updateRerankCheckpointStage(taskId, RerankTaskCheckpointStageEnum.eval_tunedmodel);
    }

    // Write final result
    const finalTask = await getRerankTrainTask(taskId);
    if (!finalTask) {
      const enhancedError = createRerankEnhancedError(
        null,
        RerankTrainErrEnum.rerankProcessorTaskLostAfterEval,
        RerankTrainSuggestionEnum.rerankProcessorTaskLostAfterEval
      );
      throw new TrainTaskUnrecoverableError(enhancedError);
    }
    const finalCheckpoint = finalTask.checkpoint.data || {};
    await MongoRerankTrainTask.updateOne(
      { _id: taskId },
      {
        status: RerankTrainTaskStatusEnum.completed,
        updateTime: new Date(),
        finishTime: new Date(),
        result: {
          trainDatasetId: finalCheckpoint.generate_trainset?.trainDatasetId ?? undefined,
          trainDatasetFilePath:
            finalCheckpoint.generate_trainset?.trainDatasetFilePath ?? undefined,
          tunedModelId: finalCheckpoint.registering?.tunedModelId ?? undefined,
          evalDatasetId: finalCheckpoint.generate_evaldataset?.evalDatasetId ?? undefined,
          baseModelEvalResult: finalCheckpoint.eval_basemodel?.baseModelEvalResult,
          tunedModelEvalResult: finalCheckpoint.eval_tunedmodel?.tunedModelEvalResult
        }
      }
    );

    addLog.info('Rerank train task completed', { taskId });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    const isUnrecoverable = error instanceof TrainTaskUnrecoverableError;

    addLog.error('Rerank train task failed', {
      taskId,
      error: errorMessage,
      isUnrecoverable,
      errorType: error instanceof Error ? error.constructor.name : 'Unknown'
    });

    throw error;
  }
};

/**
 * Determine whether to run a stage (skip completed stages, run remaining stages)
 */
function shouldRunStage(
  currentStage: `${RerankTaskCheckpointStageEnum}` | null,
  targetStage: `${RerankTaskCheckpointStageEnum}`
): boolean {
  if (currentStage === null) return true;

  const stageOrder: RerankTaskCheckpointStageEnum[] = [
    RerankTaskCheckpointStageEnum.generate_trainset,
    RerankTaskCheckpointStageEnum.generate_evaldataset,
    RerankTaskCheckpointStageEnum.eval_basemodel,
    RerankTaskCheckpointStageEnum.finetuning,
    RerankTaskCheckpointStageEnum.registering,
    RerankTaskCheckpointStageEnum.eval_tunedmodel
  ];

  const currentStageEnum = currentStage as RerankTaskCheckpointStageEnum;
  const targetStageEnum = targetStage as RerankTaskCheckpointStageEnum;

  return stageOrder.indexOf(targetStageEnum) > stageOrder.indexOf(currentStageEnum);
}
