// @ts-nocheck

export const iconPaths = {
  alignLeft: () => import('./icons/alignLeft.svg'),
  backup: () => import('./icons/backup.svg'),
  book: () => import('./icons/book.svg'),
  change: () => import('./icons/change.svg'),
  chart: () => import('./icons/chart.svg'),
  chatSend: () => import('./icons/chatSend.svg'),
  check: () => import('./icons/check.svg'),
  checkCircle: () => import('./icons/checkCircle.svg'),
  circleMinus: () => import('./icons/circleMinus.svg'),
  close: () => import('./icons/close.svg'),
  closeSolid: () => import('./icons/closeSolid.svg'),
  code: () => import('./icons/code.svg'),
  codeCopilot: () => import('./icons/codeCopilot.svg'),
  comment: () => import('./icons/comment.svg'),
  'common/add2': () => import('./icons/common/add2.svg'),
  'common/addLight': () => import('./icons/common/addLight.svg'),
  'common/administrator': () => import('./icons/common/administrator.svg'),
  'common/alipay': () => import('./icons/common/alipay.svg'),
  'common/app': () => import('./icons/common/app.svg'),
  'common/arrowLeft': () => import('./icons/common/arrowLeft.svg'),
  'common/arrowRight': () => import('./icons/common/arrowRight.svg'),
  'common/audit': () => import('./icons/common/audit.svg'),
  'common/backFill': () => import('./icons/common/backFill.svg'),
  'common/backLight': () => import('./icons/common/backLight.svg'),
  'common/billing': () => import('./icons/common/billing.svg'),
  'common/check': () => import('./icons/common/check.svg'),
  'common/clearLight': () => import('./icons/common/clearLight.svg'),
  'common/closeLight': () => import('./icons/common/closeLight.svg'),
  'common/confirm/commonTip': () => import('./icons/common/confirm/commonTip.svg'),
  'common/confirm/deleteTip': () => import('./icons/common/confirm/deleteTip.svg'),
  'common/confirm/restoreTip': () => import('./icons/common/confirm/restoreTip.svg'),
  'common/courseLight': () => import('./icons/common/courseLight.svg'),
  'common/customTitleLight': () => import('./icons/common/customTitleLight.svg'),
  'common/detail': () => import('./icons/common/detail.svg'),
  'common/dingtalkFill': () => import('./icons/common/dingtalkFill.svg'),
  'common/disable': () => import('./icons/common/disable.svg'),
  'common/downArrowFill': () => import('./icons/common/downArrowFill.svg'),
  'common/download': () => import('./icons/common/download.svg'),
  'common/downloadLine': () => import('./icons/common/downloadLine.svg'),
  'common/htmlPreview': () => import('./icons/common/htmlPreview.svg'),
  'common/edit': () => import('./icons/common/edit.svg'),
  'common/editor/resizer': () => import('./icons/common/editor/resizer.svg'),
  'common/ellipsis': () => import('./icons/common/ellipsis.svg'),
  'common/enable': () => import('./icons/common/enable.svg'),
  'common/error': () => import('./icons/common/error.svg'),
  'common/errorFill': () => import('./icons/common/errorFill.svg'),
  'common/file/move': () => import('./icons/common/file/move.svg'),
  'common/fileNotFound': () => import('./icons/common/fileNotFound.svg'),
  'common/first_page': () => import('./icons/common/first_page.svg'),
  'common/folderFill': () => import('./icons/common/folderFill.svg'),
  'common/folderImport': () => import('./icons/common/folderImport.svg'),
  'common/fullScreenLight': () => import('./icons/common/fullScreenLight.svg'),
  'common/gitFill': () => import('./icons/common/gitFill.svg'),
  'common/gitInlight': () => import('./icons/common/gitInlight.svg'),
  'common/globalLine': () => import('./icons/common/globalLine.svg'),
  'common/googleFill': () => import('./icons/common/googleFill.svg'),
  'common/help': () => import('./icons/common/help.svg'),
  'common/importLight': () => import('./icons/common/importLight.svg'),
  'common/info': () => import('./icons/common/info.svg'),
  'common/inviteLight': () => import('./icons/common/inviteLight.svg'),
  'common/language/America': () => import('./icons/common/language/America.svg'),
  'common/language/China': () => import('./icons/common/language/China.svg'),
  'common/language/en': () => import('./icons/common/language/en.svg'),
  'common/language/zh': () => import('./icons/common/language/zh.svg'),
  'common/latest_page': () => import('./icons/common/latest_page.svg'),
  'common/layer': () => import('./icons/common/layer.svg'),
  'common/leftArrowLight': () => import('./icons/common/leftArrowLight.svg'),
  'common/line': () => import('./icons/common/line.svg'),
  'common/lineChange': () => import('./icons/common/lineChange.svg'),
  'common/lineStop': () => import('./icons/common/lineStop.svg'),
  'common/link': () => import('./icons/common/link.svg'),
  'common/linkBlue': () => import('./icons/common/linkBlue.svg'),
  'common/list': () => import('./icons/common/list.svg'),
  'common/loading': () => import('./icons/common/loading.svg'),
  'common/maximize': () => import('./icons/common/maximize.svg'),
  'common/microsoft': () => import('./icons/common/microsoft.svg'),
  'common/model': () => import('./icons/common/model.svg'),
  'common/openai': () => import('./icons/common/openai.svg'),
  'common/overviewLight': () => import('./icons/common/overviewLight.svg'),
  'common/paramsLight': () => import('./icons/common/paramsLight.svg'),
  'common/paused': () => import('./icons/common/paused.svg'),
  'common/refresh': () => import('./icons/common/refresh.svg'),
  'common/refreshLight': () => import('./icons/common/refreshLight.svg'),
  'common/resultLight': () => import('./icons/common/resultLight.svg'),
  'common/retryLight': () => import('./icons/common/retryLight.svg'),
  'common/rightArrow': () => import('./icons/common/rightArrow.svg'),
  'common/rightArrowFill': () => import('./icons/common/rightArrowFill.svg'),
  'common/rightArrowLight': () => import('./icons/common/rightArrowLight.svg'),
  'common/rocket': () => import('./icons/common/rocket.svg'),
  'common/running': () => import('./icons/common/running.svg'),
  'common/searchLight': () => import('./icons/common/searchLight.svg'),
  'common/select': () => import('./icons/common/select.svg'),
  'common/selectLight': () => import('./icons/common/selectLight.svg'),
  'common/setting': () => import('./icons/common/setting.svg'),
  'common/settingLight': () => import('./icons/common/settingLight.svg'),
  'common/skill': () => import('./icons/common/skill.svg'),
  'common/solidChevronDown': () => import('./icons/common/solidChevronDown.svg'),
  'common/solidChevronUp': () => import('./icons/common/solidChevronUp.svg'),
  'common/templateMarket': () => import('./icons/common/templateMarket.svg'),
  'common/text/t': () => import('./icons/common/text/t.svg'),
  'common/thirdParty': () => import('./icons/common/thirdParty.svg'),
  'common/toolkit': () => import('./icons/common/toolkit.svg'),
  'common/trash': () => import('./icons/common/trash.svg'),
  'common/uploadFileFill': () => import('./icons/common/uploadFileFill.svg'),
  'common/upperRight': () => import('./icons/common/upperRight.svg'),
  'common/user': () => import('./icons/common/user.svg'),
  'common/userInfo': () => import('./icons/common/userInfo.svg'),
  'common/variable': () => import('./icons/common/variable.svg'),
  'common/viewLight': () => import('./icons/common/viewLight.svg'),
  'common/voiceLight': () => import('./icons/common/voiceLight.svg'),
  'common/wallet': () => import('./icons/common/wallet.svg'),
  'common/warn': () => import('./icons/common/warn.svg'),
  'common/wechat': () => import('./icons/common/wechat.svg'),
  'common/wechatFill': () => import('./icons/common/wechatFill.svg'),
  'common/wecom': () => import('./icons/common/wecom.svg'),
  configmap: () => import('./icons/configmap.svg'),
  copy: () => import('./icons/copy.svg'),
  'core/app/agent/child/contextCompress': () =>
    import('./icons/core/app/agent/child/contextCompress.svg'),
  'core/app/agent/child/contextPick': () => import('./icons/core/app/agent/child/contextPick.svg'),
  'core/app/agent/child/plan': () => import('./icons/core/app/agent/child/plan.svg'),
  'core/app/agent/child/stepCall': () => import('./icons/core/app/agent/child/stepCall.svg'),
  'core/app/agent/child/stepSummary': () => import('./icons/core/app/agent/child/stepSummary.svg'),
  'core/app/aiFill': () => import('./icons/core/app/aiFill.svg'),
  'core/app/aiLight': () => import('./icons/core/app/aiLight.svg'),
  'core/app/aiLightSmall': () => import('./icons/core/app/aiLightSmall.svg'),
  'core/app/create': () => import('./icons/core/app/create.svg'),
  'core/app/customFeedback': () => import('./icons/core/app/customFeedback.svg'),
  'core/app/headphones': () => import('./icons/core/app/headphones.svg'),
  'core/app/inputGuides': () => import('./icons/core/app/inputGuides.svg'),
  'core/app/logsLight': () => import('./icons/core/app/logsLight.svg'),
  'core/app/markLight': () => import('./icons/core/app/markLight.svg'),
  'core/app/publish/lark': () => import('./icons/core/app/publish/lark.svg'),
  'core/app/publish/offiaccount': () => import('./icons/core/app/publish/offiaccount.svg'),
  'core/app/publish/wechat': () => import('./icons/core/app/publish/wechat.svg'),
  'core/app/publish/wecom': () => import('./icons/core/app/publish/wecom.svg'),
  'core/app/sandbox/css': () => import('./icons/core/app/sandbox/css.svg'),
  'core/app/sandbox/default': () => import('./icons/core/app/sandbox/default.svg'),
  'core/app/sandbox/docx': () => import('./icons/core/app/sandbox/docx.svg'),
  'core/app/sandbox/file': () => import('./icons/core/app/sandbox/file.svg'),
  'core/app/sandbox/go': () => import('./icons/core/app/sandbox/go.svg'),
  'core/app/sandbox/html': () => import('./icons/core/app/sandbox/html.svg'),
  'core/app/sandbox/image': () => import('./icons/core/app/sandbox/image.svg'),
  'core/app/sandbox/java': () => import('./icons/core/app/sandbox/java.svg'),
  'core/app/sandbox/js': () => import('./icons/core/app/sandbox/js.svg'),
  'core/app/sandbox/md': () => import('./icons/core/app/sandbox/md.svg'),
  'core/app/sandbox/pdf': () => import('./icons/core/app/sandbox/pdf.svg'),
  'core/app/sandbox/pptx': () => import('./icons/core/app/sandbox/pptx.svg'),
  'core/app/sandbox/py': () => import('./icons/core/app/sandbox/py.svg'),
  'core/app/sandbox/sandbox': () => import('./icons/core/app/sandbox/sandbox.svg'),
  'core/app/sandbox/scss': () => import('./icons/core/app/sandbox/scss.svg'),
  'core/app/sandbox/svg': () => import('./icons/core/app/sandbox/svg.svg'),
  'core/app/sandbox/txt': () => import('./icons/core/app/sandbox/txt.svg'),
  'core/app/sandbox/video': () => import('./icons/core/app/sandbox/video.svg'),
  'core/app/sandbox/xlsx': () => import('./icons/core/app/sandbox/xlsx.svg'),
  'core/app/sandbox/yml': () => import('./icons/core/app/sandbox/yml.svg'),
  'core/app/sandbox/zip': () => import('./icons/core/app/sandbox/zip.svg'),
  'core/app/schedulePlan': () => import('./icons/core/app/schedulePlan.svg'),
  'core/app/simpleBot': () => import('./icons/core/app/simpleBot.svg'),
  'core/app/simpleMode/ai': () => import('./icons/core/app/simpleMode/ai.svg'),
  'core/app/simpleMode/autoExec': () => import('./icons/core/app/simpleMode/autoExec.svg'),
  'core/app/simpleMode/chat': () => import('./icons/core/app/simpleMode/chat.svg'),
  'core/app/simpleMode/dataset': () => import('./icons/core/app/simpleMode/dataset.svg'),
  'core/app/simpleMode/file': () => import('./icons/core/app/simpleMode/file.svg'),
  'core/app/simpleMode/tts': () => import('./icons/core/app/simpleMode/tts.svg'),
  'core/app/simpleMode/variable': () => import('./icons/core/app/simpleMode/variable.svg'),
  'core/app/simpleMode/whisper': () => import('./icons/core/app/simpleMode/whisper.svg'),
  'core/app/toolCall': () => import('./icons/core/app/toolCall.svg'),
  'core/app/type/agentFill': () => import('./icons/core/app/type/agentFill.svg'),
  'core/app/type/httpPlugin': () => import('./icons/core/app/type/httpPlugin.svg'),
  'core/app/type/httpPluginFill': () => import('./icons/core/app/type/httpPluginFill.svg'),
  'core/app/type/mcpTools': () => import('./icons/core/app/type/mcpTools.svg'),
  'core/app/type/mcpToolsFill': () => import('./icons/core/app/type/mcpToolsFill.svg'),
  'core/app/type/plugin': () => import('./icons/core/app/type/plugin.svg'),
  'core/app/type/pluginFill': () => import('./icons/core/app/type/pluginFill.svg'),
  'core/app/type/simple': () => import('./icons/core/app/type/simple.svg'),
  'core/app/type/simpleFill': () => import('./icons/core/app/type/simpleFill.svg'),
  'core/app/type/workflow': () => import('./icons/core/app/type/workflow.svg'),
  'core/app/type/workflowFill': () => import('./icons/core/app/type/workflowFill.svg'),
  'core/app/variable/input': () => import('./icons/core/app/variable/input.svg'),
  'core/chat/QGFill': () => import('./icons/core/chat/QGFill.svg'),
  'core/chat/backText': () => import('./icons/core/chat/backText.svg'),
  'core/chat/chatFill': () => import('./icons/core/chat/chatFill.svg'),
  'core/chat/chatLight': () => import('./icons/core/chat/chatLight.svg'),
  'core/chat/chatModelTag': () => import('./icons/core/chat/chatModelTag.svg'),
  'core/chat/chevronDown': () => import('./icons/core/chat/chevronDown.svg'),
  'core/chat/chevronRight': () => import('./icons/core/chat/chevronRight.svg'),
  'core/chat/chevronSelector': () => import('./icons/core/chat/chevronSelector.svg'),
  'core/chat/chevronUp': () => import('./icons/core/chat/chevronUp.svg'),
  'core/chat/feedback/badLight': () => import('./icons/core/chat/feedback/badLight.svg'),
  'core/chat/feedback/goodLight': () => import('./icons/core/chat/feedback/goodLight.svg'),
  'core/chat/fileSelect': () => import('./icons/core/chat/fileSelect.svg'),
  'core/chat/quoteFill': () => import('./icons/core/chat/quoteFill.svg'),
  'core/chat/quoteSign': () => import('./icons/core/chat/quoteSign.svg'),
  'core/chat/recordFill': () => import('./icons/core/chat/recordFill.svg'),
  'core/chat/sendFill': () => import('./icons/core/chat/sendFill.svg'),
  'core/chat/sendLight': () => import('./icons/core/chat/sendLight.svg'),
  'core/chat/setTopLight': () => import('./icons/core/chat/setTopLight.svg'),
  'core/chat/sideLine': () => import('./icons/core/chat/sideLine.svg'),
  'core/chat/sidebar/expand': () => import('./icons/core/chat/sidebar/expand.svg'),
  'core/chat/sidebar/fold': () => import('./icons/core/chat/sidebar/fold.svg'),
  'core/chat/sidebar/home': () => import('./icons/core/chat/sidebar/home.svg'),
  'core/chat/sidebar/logout': () => import('./icons/core/chat/sidebar/logout.svg'),
  'core/chat/sidebar/menu': () => import('./icons/core/chat/sidebar/menu.svg'),
  'core/chat/sidebar/star': () => import('./icons/core/chat/sidebar/star.svg'),
  'core/chat/stopSpeech': () => import('./icons/core/chat/stopSpeech.svg'),
  'core/chat/think': () => import('./icons/core/chat/think.svg'),
  'core/dataset/commonDatasetColor': () => import('./icons/core/dataset/commonDatasetColor.svg'),
  'core/dataset/commonDatasetOutline': () =>
    import('./icons/core/dataset/commonDatasetOutline.svg'),
  'core/dataset/datasetFill': () => import('./icons/core/dataset/datasetFill.svg'),
  'core/dataset/datasetLight': () => import('./icons/core/dataset/datasetLight.svg'),
  'core/dataset/datasetLightSmall': () => import('./icons/core/dataset/datasetLightSmall.svg'),
  'core/dataset/externalDatasetColor': () =>
    import('./icons/core/dataset/externalDatasetColor.svg'),
  'core/dataset/externalDatasetOutline': () =>
    import('./icons/core/dataset/externalDatasetOutline.svg'),
  'core/dataset/dingtalkDatasetColor': () =>
    import('./icons/core/dataset/dingtalkDatasetColor.svg'),
  'core/dataset/dingtalkDatasetOutline': () =>
    import('./icons/core/dataset/dingtalkDatasetOutline.svg'),
  'core/dataset/feishuDatasetColor': () => import('./icons/core/dataset/feishuDatasetColor.svg'),
  'core/dataset/feishuDatasetOutline': () =>
    import('./icons/core/dataset/feishuDatasetOutline.svg'),
  'core/dataset/fileCollection': () => import('./icons/core/dataset/fileCollection.svg'),
  'core/dataset/fullTextRecall': () => import('./icons/core/dataset/fullTextRecall.svg'),
  'core/dataset/imageFill': () => import('./icons/core/dataset/imageFill.svg'),
  'core/dataset/manualCollection': () => import('./icons/core/dataset/manualCollection.svg'),
  'core/dataset/mixedRecall': () => import('./icons/core/dataset/mixedRecall.svg'),
  'core/dataset/modeEmbedding': () => import('./icons/core/dataset/modeEmbedding.svg'),
  'core/dataset/otherDataset': () => import('./icons/core/dataset/otherDataset.svg'),
  'core/dataset/questionExtension': () => import('./icons/core/dataset/questionExtension.svg'),
  'core/dataset/searchfilter': () => import('./icons/core/dataset/searchfilter.svg'),
  'core/dataset/tag': () => import('./icons/core/dataset/tag.svg'),
  'core/dataset/websiteDataset': () => import('./icons/core/dataset/websiteDataset.svg'),
  'core/dataset/websiteDatasetColor': () => import('./icons/core/dataset/websiteDatasetColor.svg'),
  'core/dataset/websiteDatasetOutline': () =>
    import('./icons/core/dataset/websiteDatasetOutline.svg'),
  'core/dataset/yuqueDatasetColor': () => import('./icons/core/dataset/yuqueDatasetColor.svg'),
  'core/dataset/yuqueDatasetOutline': () => import('./icons/core/dataset/yuqueDatasetOutline.svg'),
  'core/modules/basicNode': () => import('./icons/core/modules/basicNode.svg'),
  'core/modules/fitView': () => import('./icons/core/modules/fitView.svg'),
  'core/modules/variable': () => import('./icons/core/modules/variable.svg'),
  'core/modules/welcomeText': () => import('./icons/core/modules/welcomeText.svg'),
  'core/skill/default': () => import('./icons/core/skill/default.svg'),
  'core/skill/help': () => import('./icons/core/skill/help.svg'),
  'core/workflow/closeEdge': () => import('./icons/core/workflow/closeEdge.svg'),
  'core/workflow/debug': () => import('./icons/core/workflow/debug.svg'),
  'core/workflow/debugBlue': () => import('./icons/core/workflow/debugBlue.svg'),
  'core/workflow/debugNext': () => import('./icons/core/workflow/debugNext.svg'),
  'core/workflow/debugResult': () => import('./icons/core/workflow/debugResult.svg'),
  'core/workflow/edgeArrow': () => import('./icons/core/workflow/edgeArrow.svg'),
  'core/workflow/edgeArrowBold': () => import('./icons/core/workflow/edgeArrowBold.svg'),
  'core/workflow/inputType/array': () => import('./icons/core/workflow/inputType/array.svg'),
  'core/workflow/inputType/conditional': () =>
    import('./icons/core/workflow/inputType/conditional.svg'),
  'core/workflow/inputType/customVariable': () =>
    import('./icons/core/workflow/inputType/customVariable.svg'),
  'core/workflow/inputType/dynamic': () => import('./icons/core/workflow/inputType/dynamic.svg'),
  'core/workflow/inputType/external': () => import('./icons/core/workflow/inputType/external.svg'),
  'core/workflow/inputType/file': () => import('./icons/core/workflow/inputType/file.svg'),
  'core/workflow/inputType/input': () => import('./icons/core/workflow/inputType/input.svg'),
  'core/workflow/inputType/internal': () => import('./icons/core/workflow/inputType/internal.svg'),
  'core/workflow/inputType/jsonEditor': () =>
    import('./icons/core/workflow/inputType/jsonEditor.svg'),
  'core/workflow/inputType/model': () => import('./icons/core/workflow/inputType/model.svg'),
  'core/workflow/inputType/multipleSelect': () =>
    import('./icons/core/workflow/inputType/multipleSelect.svg'),
  'core/workflow/inputType/numberInput': () =>
    import('./icons/core/workflow/inputType/numberInput.svg'),
  'core/workflow/inputType/option': () => import('./icons/core/workflow/inputType/option.svg'),
  'core/workflow/inputType/password': () => import('./icons/core/workflow/inputType/password.svg'),
  'core/workflow/inputType/reference': () =>
    import('./icons/core/workflow/inputType/reference.svg'),
  'core/workflow/inputType/selectApp': () =>
    import('./icons/core/workflow/inputType/selectApp.svg'),
  'core/workflow/inputType/selectDataset': () =>
    import('./icons/core/workflow/inputType/selectDataset.svg'),
  'core/workflow/inputType/selectLLM': () =>
    import('./icons/core/workflow/inputType/selectLLM.svg'),
  'core/workflow/inputType/switch': () => import('./icons/core/workflow/inputType/switch.svg'),
  'core/workflow/inputType/textarea': () => import('./icons/core/workflow/inputType/textarea.svg'),
  'core/workflow/inputType/timePointSelect': () =>
    import('./icons/core/workflow/inputType/timePointSelect.svg'),
  'core/workflow/inputType/timeRangeSelect': () =>
    import('./icons/core/workflow/inputType/timeRangeSelect.svg'),
  'core/workflow/mouse': () => import('./icons/core/workflow/mouse.svg'),
  'core/workflow/present': () => import('./icons/core/workflow/present.svg'),
  'core/workflow/publish': () => import('./icons/core/workflow/publish.svg'),
  'core/workflow/redo': () => import('./icons/core/workflow/redo.svg'),
  'core/workflow/runError': () => import('./icons/core/workflow/runError.svg'),
  'core/workflow/runSkip': () => import('./icons/core/workflow/runSkip.svg'),
  'core/workflow/runSuccess': () => import('./icons/core/workflow/runSuccess.svg'),
  'core/workflow/running': () => import('./icons/core/workflow/running.svg'),
  'core/workflow/template/BI': () => import('./icons/core/workflow/template/BI.svg'),
  'core/workflow/template/FileRead': () => import('./icons/core/workflow/template/FileRead.svg'),
  'core/workflow/template/agent': () => import('./icons/core/workflow/template/agent.svg'),
  'core/workflow/template/agentLinear': () =>
    import('./icons/core/workflow/template/agentLinear.tsx'),
  'core/workflow/template/aiChat': () => import('./icons/core/workflow/template/aiChat.svg'),
  'core/workflow/template/aiChatLinear': () =>
    import('./icons/core/workflow/template/aiChatLinear.tsx'),
  'core/workflow/template/codeRun': () => import('./icons/core/workflow/template/codeRun.svg'),
  'core/workflow/template/codeRunLinear': () =>
    import('./icons/core/workflow/template/codeRunLinear.tsx'),
  'core/workflow/template/customFeedback': () =>
    import('./icons/core/workflow/template/customFeedback.svg'),
  'core/workflow/template/customFeedbackLinear': () =>
    import('./icons/core/workflow/template/customFeedbackLinear.tsx'),
  'core/workflow/template/datasetConcat': () =>
    import('./icons/core/workflow/template/datasetConcat.svg'),
  'core/workflow/template/datasetConcatLinear': () =>
    import('./icons/core/workflow/template/datasetConcatLinear.tsx'),
  'core/workflow/template/datasetSearch': () =>
    import('./icons/core/workflow/template/datasetSearch.svg'),
  'core/workflow/template/datasetSearchLinear': () =>
    import('./icons/core/workflow/template/datasetSearchLinear.tsx'),
  'core/workflow/template/extractJson': () =>
    import('./icons/core/workflow/template/extractJson.svg'),
  'core/workflow/template/extractJsonLinear': () =>
    import('./icons/core/workflow/template/extractJsonLinear.tsx'),
  'core/workflow/template/formInput': () => import('./icons/core/workflow/template/formInput.svg'),
  'core/workflow/template/formInputLinear': () =>
    import('./icons/core/workflow/template/formInputLinear.tsx'),
  'core/workflow/template/httpRequest': () =>
    import('./icons/core/workflow/template/httpRequest.svg'),
  'core/workflow/template/httpRequestLinear': () =>
    import('./icons/core/workflow/template/httpRequestLinear.tsx'),
  'core/workflow/template/ifelse': () => import('./icons/core/workflow/template/ifelse.svg'),
  'core/workflow/template/ifelseLinear': () =>
    import('./icons/core/workflow/template/ifelseLinear.tsx'),
  'core/workflow/template/lafDispatch': () =>
    import('./icons/core/workflow/template/lafDispatch.svg'),
  'core/workflow/template/loop': () => import('./icons/core/workflow/template/loop.svg'),
  'core/workflow/template/loopEnd': () => import('./icons/core/workflow/template/loopEnd.svg'),
  'core/workflow/template/loopEndLinear': () =>
    import('./icons/core/workflow/template/loopEndLinear.tsx'),
  'core/workflow/template/loopLinear': () =>
    import('./icons/core/workflow/template/loopLinear.tsx'),
  'core/workflow/template/loopStart': () => import('./icons/core/workflow/template/loopStart.svg'),
  'core/workflow/template/loopStartLinear': () =>
    import('./icons/core/workflow/template/loopStartLinear.tsx'),
  'core/workflow/template/parallelRun': () =>
    import('./icons/core/workflow/template/parallelRun.svg'),
  'core/workflow/template/parallelRunLinear': () =>
    import('./icons/core/workflow/template/parallelRunLinear.tsx'),
  'core/workflow/template/loopRun': () => import('./icons/core/workflow/template/loopRun.svg'),
  'core/workflow/template/loopRunLinear': () =>
    import('./icons/core/workflow/template/loopRunLinear.tsx'),
  'core/workflow/template/loopRunStart': () =>
    import('./icons/core/workflow/template/loopRunStart.svg'),
  'core/workflow/template/loopRunStartLinear': () =>
    import('./icons/core/workflow/template/loopRunStartLinear.tsx'),
  'core/workflow/template/loopRunBreak': () =>
    import('./icons/core/workflow/template/loopRunBreak.svg'),
  'core/workflow/template/loopRunBreakLinear': () =>
    import('./icons/core/workflow/template/loopRunBreakLinear.tsx'),
  'core/workflow/template/mathCall': () => import('./icons/core/workflow/template/mathCall.svg'),
  'core/workflow/template/pluginOutput': () =>
    import('./icons/core/workflow/template/pluginOutput.svg'),
  'core/workflow/template/pluginOutputLinear': () =>
    import('./icons/core/workflow/template/pluginOutputLinear.tsx'),
  'core/workflow/template/queryExtension': () =>
    import('./icons/core/workflow/template/queryExtension.svg'),
  'core/workflow/template/queryExtensionLinear': () =>
    import('./icons/core/workflow/template/queryExtensionLinear.tsx'),
  'core/workflow/template/questionClassify': () =>
    import('./icons/core/workflow/template/questionClassify.svg'),
  'core/workflow/template/questionClassifyLinear': () =>
    import('./icons/core/workflow/template/questionClassifyLinear.tsx'),
  'core/workflow/template/readFiles': () => import('./icons/core/workflow/template/readFiles.svg'),
  'core/workflow/template/readFilesLinear': () =>
    import('./icons/core/workflow/template/readFilesLinear.tsx'),
  'core/workflow/template/reply': () => import('./icons/core/workflow/template/reply.svg'),
  'core/workflow/template/replyLinear': () =>
    import('./icons/core/workflow/template/replyLinear.tsx'),
  'core/workflow/template/runApp': () => import('./icons/core/workflow/template/runApp.svg'),
  'core/workflow/template/stopTool': () => import('./icons/core/workflow/template/stopTool.svg'),
  'core/workflow/template/stopToolLinear': () =>
    import('./icons/core/workflow/template/stopToolLinear.tsx'),
  'core/workflow/template/systemConfig': () =>
    import('./icons/core/workflow/template/systemConfig.svg'),
  'core/workflow/template/systemConfigLinear': () =>
    import('./icons/core/workflow/template/systemConfigLinear.tsx'),
  'core/workflow/template/textConcat': () =>
    import('./icons/core/workflow/template/textConcat.svg'),
  'core/workflow/template/textConcatLinear': () =>
    import('./icons/core/workflow/template/textConcatLinear.tsx'),
  'core/workflow/template/toolCall': () => import('./icons/core/workflow/template/toolCall.svg'),
  'core/workflow/template/toolCallLinear': () =>
    import('./icons/core/workflow/template/toolCallLinear.tsx'),
  'core/workflow/template/toolParams': () =>
    import('./icons/core/workflow/template/toolParams.svg'),
  'core/workflow/template/toolParamsLinear': () =>
    import('./icons/core/workflow/template/toolParamsLinear.tsx'),
  'core/workflow/template/toolkitActive': () =>
    import('./icons/core/workflow/template/toolkitActive.svg'),
  'core/workflow/template/toolkitInactive': () =>
    import('./icons/core/workflow/template/toolkitInactive.svg'),
  'core/workflow/template/userSelect': () =>
    import('./icons/core/workflow/template/userSelect.svg'),
  'core/workflow/template/userSelectLinear': () =>
    import('./icons/core/workflow/template/userSelectLinear.tsx'),
  'core/workflow/template/variable': () => import('./icons/core/workflow/template/variable.svg'),
  'core/workflow/template/variableUpdate': () =>
    import('./icons/core/workflow/template/variableUpdate.svg'),
  'core/workflow/template/variableUpdateLinear': () =>
    import('./icons/core/workflow/template/variableUpdateLinear.tsx'),
  'core/workflow/template/workflowStart': () =>
    import('./icons/core/workflow/template/workflowStart.svg'),
  'core/workflow/template/workflowStartLinear': () =>
    import('./icons/core/workflow/template/workflowStartLinear.tsx'),
  'core/workflow/touchTable': () => import('./icons/core/workflow/touchTable.svg'),
  'core/workflow/undo': () => import('./icons/core/workflow/undo.svg'),
  'core/workflow/upload': () => import('./icons/core/workflow/upload.svg'),
  date: () => import('./icons/date.svg'),
  delete: () => import('./icons/delete.svg'),
  drag: () => import('./icons/drag.svg'),
  edgeAdd: () => import('./icons/edgeAdd.svg'),
  edit: () => import('./icons/edit.svg'),
  empty: () => import('./icons/empty.svg'),
  export: () => import('./icons/export.svg'),
  feedback: () => import('./icons/feedback.svg'),
  'file/csv': () => import('./icons/file/csv.svg'),
  'file/fill/audio': () => import('./icons/file/fill/audio.svg'),
  'file/fill/csv': () => import('./icons/file/fill/csv.svg'),
  'file/fill/doc': () => import('./icons/file/fill/doc.svg'),
  'file/fill/file': () => import('./icons/file/fill/file.svg'),
  'file/fill/folder': () => import('./icons/file/fill/folder.svg'),
  'file/fill/html': () => import('./icons/file/fill/html.svg'),
  'file/fill/manual': () => import('./icons/file/fill/manual.svg'),
  'file/fill/markdown': () => import('./icons/file/fill/markdown.svg'),
  'file/fill/pdf': () => import('./icons/file/fill/pdf.svg'),
  'file/fill/ppt': () => import('./icons/file/fill/ppt.svg'),
  'file/fill/txt': () => import('./icons/file/fill/txt.svg'),
  'file/fill/video': () => import('./icons/file/fill/video.svg'),
  'file/fill/xlsx': () => import('./icons/file/fill/xlsx.svg'),
  'file/markdown': () => import('./icons/file/markdown.svg'),
  'file/uploadFile': () => import('./icons/file/uploadFile.svg'),
  fullScreen: () => import('./icons/fullScreen.svg'),
  help: () => import('./icons/help.svg'),
  history: () => import('./icons/history.svg'),
  image: () => import('./icons/image.svg'),
  infoRounded: () => import('./icons/infoRounded.svg'),
  invisible: () => import('./icons/invisible.svg'),
  kbTest: () => import('./icons/kbTest.svg'),
  key: () => import('./icons/key.svg'),
  keyPrimary: () => import('./icons/keyPrimary.svg'),
  loading: () => import('./icons/loading.svg'),
  'math/divide': () => import('./icons/math/divide.svg'),
  'math/equal': () => import('./icons/math/equal.svg'),
  'math/minus': () => import('./icons/math/minus.svg'),
  'math/plus': () => import('./icons/math/plus.svg'),
  'math/times': () => import('./icons/math/times.svg'),
  mcp: () => import('./icons/mcp.svg'),
  menu: () => import('./icons/menu.svg'),
  minus: () => import('./icons/minus.svg'),
  'modal/AddClb': () => import('./icons/modal/AddClb.svg'),
  'modal/changePer': () => import('./icons/modal/changePer.svg'),
  'modal/concat': () => import('./icons/modal/concat.svg'),
  'modal/edit': () => import('./icons/modal/edit.svg'),
  'modal/manualDataset': () => import('./icons/modal/manualDataset.svg'),
  'modal/selectSource': () => import('./icons/modal/selectSource.svg'),
  'modal/setting': () => import('./icons/modal/setting.svg'),
  'modal/teamPlans': () => import('./icons/modal/teamPlans.svg'),
  'model/huggingface': () => import('./icons/model/huggingface.svg'),
  more: () => import('./icons/more.svg'),
  'navbar/chatFill': () => import('./icons/navbar/chatFill.svg'),
  'navbar/chatLight': () => import('./icons/navbar/chatLight.svg'),
  'navbar/dashboardFill': () => import('./icons/navbar/dashboardFill.svg'),
  'navbar/dashboardLight': () => import('./icons/navbar/dashboardLight.svg'),
  'navbar/datasetFill': () => import('./icons/navbar/datasetFill.svg'),
  'navbar/datasetLight': () => import('./icons/navbar/datasetLight.svg'),
  'navbar/userFill': () => import('./icons/navbar/userFill.svg'),
  'navbar/userLight': () => import('./icons/navbar/userLight.svg'),
  optimizer: () => import('./icons/optimizer.svg'),
  out: () => import('./icons/out.svg'),
  paragraph: () => import('./icons/paragraph.svg'),
  'phoneTabbar/tool': () => import('./icons/phoneTabbar/tool.svg'),
  point: () => import('./icons/point.svg'),
  preview: () => import('./icons/preview.svg'),
  'price/pricearrow': () => import('./icons/price/pricearrow.svg'),
  'price/right': () => import('./icons/price/right.svg'),
  save: () => import('./icons/save.svg'),
  sliderTag: () => import('./icons/sliderTag.svg'),
  star: () => import('./icons/star.svg'),
  stop: () => import('./icons/stop.svg'),
  'support/account/coupon': () => import('./icons/support/account/coupon.svg'),
  'support/account/customDomain/provider/aliyun': () =>
    import('./icons/support/account/customDomain/provider/aliyun.svg'),
  'support/account/customDomain/provider/tencent': () =>
    import('./icons/support/account/customDomain/provider/tencent.svg'),
  'support/account/customDomain/provider/volcengine': () =>
    import('./icons/support/account/customDomain/provider/volcengine.svg'),
  'support/account/laf': () => import('./icons/support/account/laf.svg'),
  'support/account/loginoutLight': () => import('./icons/support/account/loginoutLight.svg'),
  'support/account/plans': () => import('./icons/support/account/plans.svg'),
  'support/account/promotionLight': () => import('./icons/support/account/promotionLight.svg'),
  'support/bill/extraDatasetsize': () => import('./icons/support/bill/extraDatasetsize.svg'),
  'support/bill/payRecordLight': () => import('./icons/support/bill/payRecordLight.svg'),
  'support/bill/priceLight': () => import('./icons/support/bill/priceLight.svg'),
  'support/bill/shoppingCart': () => import('./icons/support/bill/shoppingCart.svg'),
  'support/bill/wallet': () => import('./icons/support/bill/wallet.svg'),
  'support/config/configFill': () => import('./icons/support/config/configFill.svg'),
  'support/config/configLight': () => import('./icons/support/config/configLight.svg'),
  'support/outlink/apikeyFill': () => import('./icons/support/outlink/apikeyFill.svg'),
  'support/permission/collaborator': () => import('./icons/support/permission/collaborator.svg'),
  'support/permission/privateLight': () => import('./icons/support/permission/privateLight.svg'),
  'support/permission/publicLight': () => import('./icons/support/permission/publicLight.svg'),
  'support/team/group': () => import('./icons/support/team/group.svg'),
  'support/usage/usageRecordLight': () => import('./icons/support/usage/usageRecordLight.svg'),
  'support/user/informLight': () => import('./icons/support/user/informLight.svg'),
  'support/user/userFill': () => import('./icons/support/user/userFill.svg'),
  'support/user/userLight': () => import('./icons/support/user/userLight.svg'),
  'support/user/userLightSmall': () => import('./icons/support/user/userLightSmall.svg'),
  'support/user/usersLight': () => import('./icons/support/user/usersLight.svg'),
  text: () => import('./icons/text.svg'),
  union: () => import('./icons/union.svg'),
  upload: () => import('./icons/upload.svg'),
  user: () => import('./icons/user.svg'),
  visible: () => import('./icons/visible.svg'),
  wx: () => import('./icons/wx.svg')
};
