# 使用官方Python运行时作为父镜像
FROM python:3.8

# 设置工作目录
WORKDIR /app

# 将当前目录内容复制到容器的/app中
ADD . /app

RUN pip install --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple pip
# 安装程序需要的包
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r requirements.txt 

RUN python -m nltk.downloader punkt

# 运行时监听的端口
EXPOSE 6010

# 运行app.py时的命令及其参数
CMD ["python", "main.py"]
