import type {
  EmbeddingTrainsetStatusEnum,
  EmbeddingTrainDataSourceEnum,
  EmbeddingTrainTaskStatusEnum,
  EmbeddingTaskCheckpointStageEnum,
  EmbeddingTrainTypeEnum
} from './constants';
import type { EnhancedErrorMessage } from './error';

/**
 * Embedding evaluation detailed results
 * Aligned with RerankDiTingDetailedResults (MRR, NDCG, MAP, Precision)
 */
export interface EmbeddingDiTingDetailedResults {
  embed_top5_mrr?: number;
  embed_top5_ndcg?: number;
  embed_top5_map?: number;
  embed_top5_precision?: number;
  embed_top10_mrr?: number;
  embed_top10_ndcg?: number;
  embed_top10_map?: number;
  embed_top10_precision?: number;
  embed_top15_mrr?: number;
  embed_top15_ndcg?: number;
  embed_top15_map?: number;
  embed_top15_precision?: number;
  overall_mrr?: number;
  overall_ndcg?: number;
  overall_map?: number;
  overall_precision?: number;
  [key: string]: any;
}

/**
 * Embedding evaluation result
 */
export interface EmbeddingEvalResult {
  detailed_results: EmbeddingDiTingDetailedResults;
  mrr_scores?: Record<string, number[]>;
  ndcg_scores?: Record<string, number[]>;
  map_scores?: Record<string, number[]>;
  precision_scores?: Record<string, number[]>;
  retrieval_ranks?: number[][];
  column_stats?: Record<string, any>;
  total_rows?: number;
  expect_count?: number;
}

/** Trainset statistics (dynamically calculated, not stored in DB) */
export interface EmbeddingTrainsetStatistics {
  dataCount: number;
  positiveCount: number;
  negativeCount: number;
  sourceSummary: Array<
    | {
        type: 'dataset';
        count: number;
        datasetInfo: {
          datasetId: string;
        };
      }
    | {
        type: 'chat_log';
        count: number;
        chatLogInfo: {
          chatId: string;
        };
      }
    | {
        type: 'manual';
        count: number;
        manualInfo: {
          creator: string;
        };
      }
  >;
}

/** Embedding trainset schema */
export type EmbeddingTrainsetSchemaType = {
  _id: string;
  teamId: string;
  tmbId: string;

  name: string;
  description?: string;

  status: `${EmbeddingTrainsetStatusEnum}`;
  errorMsg?: EnhancedErrorMessage;

  jobId?: string;

  createTime: Date;
  updateTime: Date;

  statistics?: EmbeddingTrainsetStatistics;
};

/** Embedding training data schema */
export type EmbeddingTrainsetDataSchemaType = {
  _id: string;
  trainsetId: string;
  teamId: string;

  query: string;
  positiveDocs: string[];
  negativeDocs: string[];

  source: `${EmbeddingTrainDataSourceEnum}`;

  metadata: {
    sourceInfo: {
      datasetInfo?: {
        dataId: string;
        datasetId: string;
      };

      chatLogInfo?: {
        chatId: string;
        itemIds: string[];
      };

      manualInfo?: {
        creator: string;
        createdAt: Date;
        reason?: string;
      };
    };

    generateConfig?: {
      sampleSize?: number;
      forceRegenerate?: boolean;
      minNegativeSamples?: number;
      maxNegativeSamples?: number;
      includeOriginalQ?: boolean;
    };
  };

  createTime: Date;
};

/** Embedding training task schema */
export type EmbeddingTrainTaskSchemaType = {
  _id: string;
  teamId: string;
  tmbId: string;

  name: string;
  /** Base model ID (BaseModelItemType.model) */
  baseModelId: string;
  baseModelEndpoint: {
    base_url?: string;
    api_key?: string;
    model: string;
  };

  /** Training type: lora or ptuning, defaults to lora */
  trainType?: `${EmbeddingTrainTypeEnum}`;

  /** Train dataset ID (exact mode: passed at create; auto mode: written by generate_trainset stage) */
  trainsetId?: string;
  /** Eval dataset ID (exact mode: passed at create; auto mode: written by generate_evaldataset stage) */
  evalDatasetId?: string;
  /** Knowledge base IDs used for trainset/evaldataset generation and model evaluation */
  datasetIds: string[];
  /** Optional name for the trained model */
  newModelName?: string;

  status: EmbeddingTrainTaskStatusEnum;

  checkpoint: {
    stage: `${EmbeddingTaskCheckpointStageEnum}` | null;
    data?: {
      generate_trainset?: {
        trainDatasetId: string;
        trainDatasetFilePath: string;
        /** true = trainset was auto-generated by this task; false/absent = user-provided (exact mode) */
        autoGenerated?: boolean;
      };

      generate_evaldataset?: {
        evalDatasetId: string;
        /** true = eval dataset was auto-generated by this task; false/absent = user-provided (exact mode) */
        autoGenerated?: boolean;
      };

      eval_basemodel?: {
        baseModelEvalResult: EmbeddingEvalResult;
      };

      finetuning?: {
        sftTaskId: string;
        tunedModelEndpoint: {
          base_url: string;
          api_key: string;
          model: string;
        };
      };

      registering?: {
        tunedModelId: string;
      };

      eval_tunedmodel?: {
        tunedModelEvalResult: EmbeddingEvalResult;
      };
    };
    stageEndTime?: {
      generate_trainset?: Date;
      generate_evaldataset?: Date;
      eval_basemodel?: Date;
      finetuning?: Date;
      registering?: Date;
      eval_tunedmodel?: Date;
    };
  };

  result?: {
    trainDatasetId: string;
    trainDatasetFilePath: string;
    tunedModelId: string;
    evalDatasetId: string;
    baseModelEvalResult: EmbeddingEvalResult;
    tunedModelEvalResult: EmbeddingEvalResult;
  };

  errorMsg?: EnhancedErrorMessage;

  jobId?: string;

  createTime: Date;
  updateTime: Date;
  finishTime?: Date;
};
