// This file is generated by scripts/generate-i18n-resource-loaders.mjs.
// Do not edit manually.
import common from '../en/common.json';
import dataset from '../en/dataset.json';
import app from '../en/app.json';
import file from '../en/file.json';
import publish from '../en/publish.json';
import workflow from '../en/workflow.json';
import user from '../en/user.json';
import chat from '../en/chat.json';
import login from '../en/login.json';
import account_info from '../en/account_info.json';
import account_usage from '../en/account_usage.json';
import account_bill from '../en/account_bill.json';
import discount_coupon from '../en/discount_coupon.json';
import apikey from '../en/apikey.json';
import account_setting from '../en/account_setting.json';
import account_inform from '../en/account_inform.json';
import account_thirdParty from '../en/account_thirdParty.json';
import account from '../en/account.json';
import account_team from '../en/account_team.json';
import account_custom_domain from '../en/account_custom_domain.json';
import config from '../en/config.json';
import config_model from '../en/config_model.json';
import system_migration from '../en/system_migration.json';
import marketplace from '../en/marketplace.json';
import dashboard_mcp from '../en/dashboard_mcp.json';
import dashboard_evaluation from '../en/dashboard_evaluation.json';
import admin from '../en/admin.json';
import skill from '../en/skill.json';
import price from '../en/price.json';

export default {
  common,
  dataset,
  app,
  file,
  publish,
  workflow,
  user,
  chat,
  login,
  account_info,
  account_usage,
  account_bill,
  discount_coupon,
  apikey,
  account_setting,
  account_inform,
  account_thirdParty,
  account,
  account_team,
  account_custom_domain,
  config,
  config_model,
  system_migration,
  marketplace,
  dashboard_mcp,
  dashboard_evaluation,
  admin,
  skill,
  price
};
