// This file is generated by scripts/generate-i18n-resource-loaders.mjs.
// Do not edit manually.
import common from '../ko-KR/common.json';
import dataset from '../ko-KR/dataset.json';
import app from '../ko-KR/app.json';
import file from '../ko-KR/file.json';
import publish from '../ko-KR/publish.json';
import workflow from '../ko-KR/workflow.json';
import user from '../ko-KR/user.json';
import chat from '../ko-KR/chat.json';
import login from '../ko-KR/login.json';
import account_info from '../ko-KR/account_info.json';
import account_usage from '../ko-KR/account_usage.json';
import account_bill from '../ko-KR/account_bill.json';
import discount_coupon from '../ko-KR/discount_coupon.json';
import apikey from '../ko-KR/apikey.json';
import account_setting from '../ko-KR/account_setting.json';
import account_inform from '../ko-KR/account_inform.json';
import account_thirdParty from '../ko-KR/account_thirdParty.json';
import account from '../ko-KR/account.json';
import account_team from '../ko-KR/account_team.json';
import account_custom_domain from '../ko-KR/account_custom_domain.json';
import config from '../ko-KR/config.json';
import config_model from '../ko-KR/config_model.json';
import system_migration from '../ko-KR/system_migration.json';
import marketplace from '../ko-KR/marketplace.json';
import dashboard_mcp from '../ko-KR/dashboard_mcp.json';
import dashboard_evaluation from '../ko-KR/dashboard_evaluation.json';
import admin from '../ko-KR/admin.json';
import skill from '../ko-KR/skill.json';
import price from '../ko-KR/price.json';

export default {
  common,
  dataset,
  app,
  file,
  publish,
  workflow,
  user,
  chat,
  login,
  account_info,
  account_usage,
  account_bill,
  discount_coupon,
  apikey,
  account_setting,
  account_inform,
  account_thirdParty,
  account,
  account_team,
  account_custom_domain,
  config,
  config_model,
  system_migration,
  marketplace,
  dashboard_mcp,
  dashboard_evaluation,
  admin,
  skill,
  price
};
