// This file is generated by scripts/generate-i18n-resource-loaders.mjs.
// Do not edit manually.
import common from '../zh-Hant/common.json';
import dataset from '../zh-Hant/dataset.json';
import app from '../zh-Hant/app.json';
import file from '../zh-Hant/file.json';
import publish from '../zh-Hant/publish.json';
import workflow from '../zh-Hant/workflow.json';
import user from '../zh-Hant/user.json';
import chat from '../zh-Hant/chat.json';
import login from '../zh-Hant/login.json';
import account_info from '../zh-Hant/account_info.json';
import account_usage from '../zh-Hant/account_usage.json';
import account_bill from '../zh-Hant/account_bill.json';
import discount_coupon from '../zh-Hant/discount_coupon.json';
import apikey from '../zh-Hant/apikey.json';
import account_setting from '../zh-Hant/account_setting.json';
import account_inform from '../zh-Hant/account_inform.json';
import account_thirdParty from '../zh-Hant/account_thirdParty.json';
import account from '../zh-Hant/account.json';
import account_team from '../zh-Hant/account_team.json';
import account_custom_domain from '../zh-Hant/account_custom_domain.json';
import config from '../zh-Hant/config.json';
import config_model from '../zh-Hant/config_model.json';
import system_migration from '../zh-Hant/system_migration.json';
import marketplace from '../zh-Hant/marketplace.json';
import dashboard_mcp from '../zh-Hant/dashboard_mcp.json';
import dashboard_evaluation from '../zh-Hant/dashboard_evaluation.json';
import admin from '../zh-Hant/admin.json';
import skill from '../zh-Hant/skill.json';
import price from '../zh-Hant/price.json';

export default {
  common,
  dataset,
  app,
  file,
  publish,
  workflow,
  user,
  chat,
  login,
  account_info,
  account_usage,
  account_bill,
  discount_coupon,
  apikey,
  account_setting,
  account_inform,
  account_thirdParty,
  account,
  account_team,
  account_custom_domain,
  config,
  config_model,
  system_migration,
  marketplace,
  dashboard_mcp,
  dashboard_evaluation,
  admin,
  skill,
  price
};
