name: 'FastGPT-Pro-Test'
on:
  pull_request_target:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
      - name: Update submodules
        run: |
          if [ -f .gitmodules ]; then
            git submodule update --init --recursive
          fi
      - name: Install system deps for node-canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install Deps
        run: pnpm install
      - name: Test
        run: pnpm run test
      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
