import { cliCommandRegistry, renderHelp } from '../src';
import { describe, expect, it } from 'vitest';

describe('cliCommandRegistry', () => {
  it('registers exactly the PR1 through PR4 command surface once', () => {
    const snapshot = cliCommandRegistry.map((definition) => ({
      path: definition.path.join(' '),
      introducedIn: definition.introducedIn,
      kind: definition.kind,
      supportsDryRun: definition.supportsDryRun,
      confirm: definition.confirm,
      options: definition.options.map((item) => item.name)
    }));
    expect(new Set(snapshot.map((item) => item.path)).size).toBe(snapshot.length);
    expect(snapshot).toMatchInlineSnapshot(`
      [
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "localMutation",
          "options": [
            "--name",
            "--dry-run",
          ],
          "path": "init",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "artifact",
          "options": [
            "--output",
          ],
          "path": "build",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--input",
            "--dry-run",
          ],
          "path": "import",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "query",
          "options": [],
          "path": "inspect",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "query",
          "options": [],
          "path": "meta show",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--name",
            "--intro",
            "--dry-run",
          ],
          "path": "meta set",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "query",
          "options": [],
          "path": "config list",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "query",
          "options": [
            "--path",
          ],
          "path": "config get",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--path",
            "--value",
            "--value-json",
            "--value-file",
            "--value-env",
            "--dry-run",
          ],
          "path": "config set",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--path",
            "--dry-run",
          ],
          "path": "config unset",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "query",
          "options": [],
          "path": "variable list",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--key",
            "--type",
            "--value-type",
            "--label",
            "--description",
            "--required",
            "--config-json",
            "--config-file",
            "--options-json",
            "--min",
            "--max",
            "--max-length",
            "--time-granularity",
            "--value",
            "--value-json",
            "--value-file",
            "--value-env",
            "--dry-run",
          ],
          "path": "variable add",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--key",
            "--new-key",
            "--type",
            "--value-type",
            "--label",
            "--description",
            "--required",
            "--optional",
            "--config-json",
            "--config-file",
            "--options-json",
            "--min",
            "--max",
            "--max-length",
            "--time-granularity",
            "--value",
            "--value-json",
            "--value-file",
            "--value-env",
            "--dry-run",
          ],
          "path": "variable update",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--key",
            "--dry-run",
          ],
          "path": "variable remove",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "query",
          "options": [
            "--kind",
          ],
          "path": "template list",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "query",
          "options": [
            "--template",
          ],
          "path": "template show",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "query",
          "options": [
            "--type",
            "--parent",
          ],
          "path": "node list",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "query",
          "options": [
            "--node",
          ],
          "path": "node show",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "localMutation",
          "options": [
            "--node",
            "--template",
            "--name",
            "--after",
            "--parent",
            "--position",
            "--dry-run",
          ],
          "path": "node add",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--node",
            "--name",
            "--position",
            "--catch-error",
            "--no-catch-error",
            "--dry-run",
          ],
          "path": "node update",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "localMutation",
          "options": [
            "--node",
            "--position",
            "--parent",
            "--root",
            "--dry-run",
          ],
          "path": "node move",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "localMutation",
          "options": [
            "--from",
            "--to",
            "--template",
            "--id",
            "--position",
            "--dry-run",
          ],
          "path": "node insert",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--node",
            "--id",
            "--position",
            "--offset",
            "--dry-run",
          ],
          "path": "node clone",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--node",
            "--dry-run",
          ],
          "path": "node remove",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "query",
          "options": [
            "--node",
            "--kind",
          ],
          "path": "edge list",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--from",
            "--to",
            "--dry-run",
          ],
          "path": "edge connect",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--from",
            "--to",
            "--dry-run",
          ],
          "path": "edge disconnect",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--from",
            "--old-to",
            "--to",
            "--dry-run",
          ],
          "path": "edge reconnect",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "query",
          "options": [
            "--node",
          ],
          "path": "input list",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "query",
          "options": [
            "--node",
            "--key",
          ],
          "path": "input show",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "localMutation",
          "options": [
            "--node",
            "--key",
            "--value-type",
            "--mode",
            "--label",
            "--description",
            "--required",
            "--dry-run",
          ],
          "path": "input add",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "localMutation",
          "options": [
            "--node",
            "--key",
            "--dry-run",
          ],
          "path": "input remove",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "localMutation",
          "options": [
            "--node",
            "--key",
            "--value",
            "--value-json",
            "--value-file",
            "--value-env",
            "--dry-run",
          ],
          "path": "input set",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "localMutation",
          "options": [
            "--node",
            "--key",
            "--from",
            "--dry-run",
          ],
          "path": "input ref",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "localMutation",
          "options": [
            "--node",
            "--key",
            "--dry-run",
          ],
          "path": "input unset",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR2",
          "kind": "query",
          "options": [
            "--node",
            "--key",
          ],
          "path": "input available",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "query",
          "options": [
            "--node",
          ],
          "path": "output list",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "localMutation",
          "options": [
            "--node",
            "--key",
            "--value-type",
            "--label",
            "--description",
            "--dry-run",
          ],
          "path": "output add",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "localMutation",
          "options": [
            "--node",
            "--key",
            "--dry-run",
          ],
          "path": "output remove",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "query",
          "options": [
            "--tool-call",
          ],
          "path": "tool list",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "localMutation",
          "options": [
            "--tool-call",
            "--template",
            "--tool-node",
            "--id",
            "--position",
            "--dry-run",
          ],
          "path": "tool attach",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "localMutation",
          "options": [
            "--tool-call",
            "--tool-node",
            "--dry-run",
          ],
          "path": "tool detach",
          "supportsDryRun": true,
        },
        {
          "confirm": "none",
          "introducedIn": "PR3",
          "kind": "query",
          "options": [
            "--node",
          ],
          "path": "container children",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR1",
          "kind": "query",
          "options": [],
          "path": "validate",
          "supportsDryRun": false,
        },
        {
          "confirm": "none",
          "introducedIn": "PR4",
          "kind": "artifact",
          "options": [
            "--input",
            "--output",
          ],
          "path": "changeset plan",
          "supportsDryRun": false,
        },
        {
          "confirm": "checksum",
          "introducedIn": "PR4",
          "kind": "localMutation",
          "options": [
            "--plan",
            "--dry-run",
            "--confirm",
          ],
          "path": "changeset apply",
          "supportsDryRun": true,
        },
      ]
    `);
  });
});

describe('renderHelp', () => {
  it('derives global and command help from the registry', () => {
    const help = renderHelp();
    expect(help).toContain('template show');
    expect(help).toContain('input ref');
    expect(help).toContain('changeset plan');
    expect(help).toContain('changeset apply');
    expect(
      renderHelp(cliCommandRegistry.find((item) => item.path.join(' ') === 'build'))
    ).toContain('--output <value> (required)');
  });
});
